### ISSUE TITLE
Unable to use OpenAIGPTEmbeddings

### ISSUE THREAD

**Issue by laibamehnaz** [flairNLP/flair#1003]
I am trying to use OpenAIGPTEmbeddings but this is the error that I get : 
 cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous

Can i get some help

**Comment by stefan-it** [comment]
@laibamehnaz Could you try the latest `master` version of flair? Several tokenization errors were fixed and other Transformer-based embeddings can be used, for more information see [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md#pytorch-transformers).

You can install latest flair from `master` with:

```bash
pip install --upgrade git+https://github.com/zalandoresearch/flair.git
```

If the error still remains, please provide a code snippet so that we can look into it :)

**Comment by alanakbik** [comment]
We've updated the transformer embeddings implementation. Can you try again with: 

```python
from flair.embeddings import TransformerWordEmbeddings

# init GPT-2 embeddings
embeddings = TransformerWordEmbeddings('gpt2')

# embed a sentence
sentence = Sentence('The grass is green')
embeddings.embed(sentence)
```
