### ISSUE TITLE
How to train a flair LM on short unrelated documents

### ISSUE THREAD

**Issue by mkierans** [flairNLP/flair#1011]
I have many (millions) of short documents (~50 words) that are unrelated to each other. I would like to train a flair language model on this corpus.

Are there any suggestions on how to handle this case? The issue I am having with [Tutorial 9](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md) is that I can't figure out how to structure my text file so that it doesn't concatenate all my unrelated documents right after one another. The LM struggles to learn the relationships I want it to be paying attention to when it is fed data like this.

Has anyone else encountered a similar problem and found a good solution?

**Comment by BernierCR** [comment]
That's a good question and may be relevant to my use case. So I'm interesting in finding out more.

But, to my current understanding, doesn't it already split by newline by default? Changable to another character if needed. If you have newlines in your documents, set it to some other separator that never appears in your data. 

But I'm not the expert at this yet.

**Comment by alanakbik** [comment]
Hello @mkierans by default documents get split by line breaks and shuffled. So you could put each short document into one line. As @BernierCR wrote this means you'd have to remove all newlines from your doc or replace them with some special character, but this should work with the current code. 

I also like the idea of specifying altertative separators so that newlines can be kept - we can probably add this feature the next time we refactor the LanguageModelTrainer.

**Comment by mkierans** [comment]
Please let me know if I have this wrong, but by my understanding:

I can see that the documents can have their lines shuffled in the TextDataset class. However, once the lines are shuffled, characters for the whole text file are appended one after the other (new line is just another character), and put into a 1-d tensor. There is no special handling of new lines after the lines are shuffled, so it is possible (likely in my case) for one training sample to contain characters sequences from two different documents (lines in the text file).

The effect of this is small when training under conditions where sequence_length (parameter of training) << document length, but it is significant in my case where my documents are short.

**Comment by BernierCR** [comment]
This effects me too. I have very short documents, in the range from one word to several sentences. I am also unsure what a good sequence_length would be for this scenario. 

If you  kept them in order, then some documents would be related to nearby documents, but shuffled, nope. They are all from the same domain with not a huge amount of diversity relative to all of English. I'm unsure the size of effect this cases. 

Any ideas? Thanks.

**Comment by akhilpatelpatlolla** [comment]
Can we retrain flair model for general phone conversations? If yes, can you please share the training document format? Do I need to label text?

**Comment by mkierans** [comment]
Hi @alanakbik , thanks for taking a look at this. Can you please comment on my previous post? It seems there are other people that are also facing the same issue as me.

**Comment by alanakbik** [comment]
Hi all, yes unrelated short documents would get appended into one long sequence in which each document is separated by a special character (we use a newline for this). You're right that this is potentially problematic since the last hidden state is passed on from an unrelated document to initialize the first hidden state of another, which makes little sense. 

However, in practice this may have little impact: if you use a consistent separation character there is a good chance that the RNN will learn that once it reaches this character it makes no sense to carry over any information from the previous document. I.e. the RNN will learn to understand that a document separator really means that a completely new document begins at this position, so it would not relate them. Hope this helps!
