### ISSUE TITLE
How do i make own training model for NER?

### ISSUE THREAD

**Issue by OguzKircicek** [flairNLP/flair#1207]
A clear and concise description of what you want to know.
Hi friends , I have data for NER but I don't know how to train. I have to work with my own efficiency for doing it for Turkish. Type is ready name, locations,date etc.

**Comment by alanakbik** [comment]
Hello @OguzKircicek there are a lot of tutorials on our github page on this, specifically [this tutorial](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-sequence-labeling-model) explains how to train your own NER model. But this is tutorial 7, so you should look through tutorials 1-6 before going through this one.

**Comment by amit8121** [comment]
@OguzKircicek  not entirely sure if you're looking for a proper format in which you need to have your data in, so that you could plug it in `Sequence Tagger` and start to train. 

If so, the following is the actual format, please make sure you have a text file for train, dev and test in this format:
Ex: say there are two words ( word1, word2 ) in each of your sentences and there are 3 sentences in total, 

```
word1 POS-tag Label
word2 POS-tag Label
# empty line separator ( "\n\n" you have to separate each sentence with this empty line separator)

word1 POS-tag Label
word2 POS-tag Label

word1 POS-tag Label
word2 POS-tag Label

```

Hope this helps.

**Comment by jayurbain** [comment]
amit8121

Thank you for your answer. It took me a long time to figure this out. It would be helpful to include this in a tutorial or add to documentation.

**Comment by quadrupole** [comment]
> @OguzKircicek not entirely sure if you're looking for a proper format in which you need to have your data in, so that you could plug it in `Sequence Tagger` and start to train.
> 
> If so, the following is the actual format, please make sure you have a text file for train, dev and test in this format:
> Ex: say there are two words ( word1, word2 ) in each of your sentences and there are 3 sentences in total,
> 
> ```
> word1 POS-tag Label
> word2 POS-tag Label
> # empty line separator ( "\n\n" you have to separate each sentence with this empty line separator)
> 
> word1 POS-tag Label
> word2 POS-tag Label
> 
> word1 POS-tag Label
> word2 POS-tag Label
> ```
> 
> Hope this helps.

In this example, does this assume that in each sentence, there is always a space between the potential named entities that we tag? What if in my dataset my sentences contain run-on words like "Jack'sdog's name isJohn", and here the tags are "Jack's" -> Label1, "dog's" -> Label2, "name" -> Label3 etc. I am not able to split these entities, because I wish to make NER predictions based on data that will appear in this format during the inference stage. How do we specify the training data in this case?

**Comment by alanakbik** [comment]
Hi @quadrupole there does not need to be a space between each token, but you must have a tokenizer that can split a sentence into tokens. Since NER here is modeled as a word-level prediction task the column format assumes that tokens have already been determined.

**Comment by quadrupole** [comment]
@alanakbik Thanks got it! In other words Flair does not support NER at the character level at this moment. Since this is something that I am interested in I will try to develop it using the Flair interface. Is this something that the community would be interested in?

**Comment by djstrong** [comment]
It does not require any changes in Flair. You have to create dataset where each Token is a character (and take into consideration spaces). Maybe evaluation metric should be different.

**Comment by alanakbik** [comment]
@quadrupole absolutely, we'd appreciate a contribution! As @djstrong writes, the easiest way to do it would be to use current classes and put each character in a Token object, though maybe there are also other, more efficient options involving new classes. Let us know your progress and if you have any questions!

**Comment by djstrong** [comment]
I have not seen speed difference between operating on normal tokens and character tokens - that is odd. But, as @alanakbik said, there might be places to improve, e.g. assigning Flair embeddings to flair.Tokens and then passing the concatenation to LSTM.

**Comment by sayak1711** [comment]
For training my custom ner how can I make sure that it identifies entities like money as well as is present in the ner-ontonotes model? Can we mention ner-ontonotes as a base model on which it will add its new learning?
