### ISSUE TITLE
How to use BERT/ any other SOTA model for ENTITY extraction from a Sequence without classification in the NER task?

### ISSUE THREAD

**Issue by ManojPrabhakar** [flairNLP/flair#1237]
My requirement here is given a sentence(sequence), I would like to just extract the entities present in the sequence without classifying them to a type in the NER task. 
I see that BertForTokenClassification for NER does the classification. Can this be adapted for just the entity extraction?

Can you give me an idea of how to do entity extraction/identification using BERT or any other SOTA  model?

**Comment by alanakbik** [comment]
@ManojPrabhakar the easiest would be to use one of the pre-trained classifiers to get the entities and just ignore the type classification. 

Otherwise, you could train your own sequence labeler to find just entities without classifying them. You would need appropriate training data for this. You could modify existing training data for NER and remove the entity type annotations, then train your tagger with [the steps outlined here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-sequence-labeling-model).
