### ISSUE TITLE
Append proxy params passing in load methods

### ISSUE THREAD

**Issue by ivan339339** [flairNLP/flair#1249]
Hi,
In current version there is no possibility to set proxy params or to pass them in load method, so usage behind the proxy will cause `<urlopen error [Errno 111] Connection refused>`. It could be better if there will be any methods to set proxy or to pass proxyDict through loading methods.

**Comment by dwang888** [comment]
when "TARSClassifier.load("tars-base")", it will have error:
ConnectionError: HTTPSConnectionPool(host='nlp.informatik.hu-berlin.de', port=443): Max retries exceeded with url: /resources/models/tars-base/tars-base-v8.pt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e02bb78e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Please do add proxy in load methods. thanks!
