### ISSUE TITLE
XLNet and BERT embedding sizes are bigger than the values mentioned in the original papers

### ISSUE THREAD

**Issue by 0x7A31C7** [flairNLP/flair#1261]
### Description

In Flair, the embedding sizes for XLNet and BERT models are 2 or 4 times bigger than the values mentioned in the original papers.

The [xlnet repo](https://github.com/zihangdai/xlnet#released-models) mentions the following sizes:
`xlnet-large-cased`: **1024**-hidden
`xlnet-base-cased`: **768**-hidden

The [bert repo](https://github.com/google-research/bert#bert) mentions a hidden vector size of **1024** for `bert-large-uncased`.

### To Reproduce

```python
from flair.embeddings import XLNetEmbeddings, BertEmbeddings

xlnet_large = XLNetEmbeddings('xlnet-large-cased')
xlnet_base = XLNetEmbeddings('xlnet-base-cased')
bert = BertEmbeddings('bert-large-uncased')

print(f'XLNet large: {xlnet_large.embedding_length}') # Output: 2048
print(f'XLNet base: {xlnet_base.embedding_length}') # Output: 1536
print(f'BERT: {bert.embedding_length}') # Output: 4096
```

### Environment Info

- Ubuntu
- Python 3.7
- Flair 0.4.3

**Comment by stefan-it** [comment]
Hi @0x7A31C7 ,

the returned sizes (dimensions) mainly depend on two parameters: a) number of used layers and b) pooling operation.

Almost all Transformer-based architectures rely on subword tokenization. E.g. the original token "Johanson" could be splitted into two subtokens "johan" and "##son". The BERT paper uses the first subword embedding (resulting in a dimension size of 1024) and the last four layers of the model. The last four layers are concatenated, so there's a final dimension size of 4 (number of layers) * 1024 = 4096.

For the XLNet paper did not mention any evaluation on NER tasks. I made some experiments and it turns out, that using the first and last subword embedding leads to better results (compared to using the first subword only). First and last subword means a dimension size of 2 * 768 = 1536 for the base model and 2 * 1024 = 2048 for the large XLNet model.

I hope this helps :)
