### ISSUE TITLE
How to use flairembedding models to POS tag sentences

### ISSUE THREAD

**Issue by bbkgh** [flairNLP/flair#1314]
Hi. Thanks for great library.
I want to POS tag Persian sentences. Is there anyway to use pre-trained existing model for this purpose ?
I found FlairEmbeddings("fa-forward") but i don't know how to use embedding for POS tagging of sentences. Is there any simple way to use "fa-forward" model to POS tag sentences? (and how about NER with this model?)
I found that @stefan-it use this model/embedding to evaluate model by POS tagging (in [this repo](https://github.com/stefan-it/flair-pos-tagging) ) but i can't understand how.
Is there any _code_/doc example for this purpose?

**Comment by djstrong** [comment]
There are no pretrained models for POS tagging. You have to train one (you may use pretrained `FlairEmbeddings`).

**Comment by alanakbik** [comment]
@bbkgh yes we don't yet include a trained model for Persian text, but include datasets and embeddings for Persian, so it is easy to train your own model for POS. Use this code: 

```python
from typing import List

from flair.data import Corpus
from flair.datasets import UD_PERSIAN
from flair.embeddings import (StackedEmbeddings,
                              TokenEmbeddings, WordEmbeddings, FlairEmbeddings, BytePairEmbeddings)
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer

corpus: Corpus = UD_PERSIAN(in_memory=True)
tag_type = 'upos'

tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

embedding_types: List[TokenEmbeddings] = [
    WordEmbeddings('fa'),
    FlairEmbeddings('fa-forward'),
    FlairEmbeddings('fa-backward'),
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type)

trainer: ModelTrainer = ModelTrainer(tagger, corpus)
trainer.train('output/models/persian-pos/',
              train_with_dev=False,
              max_epochs=150) 
```

You can play around with the parameters to see if you can train a better model. For instance, you could use `BytePairEmbeddings` instead of `WordEmbeddings`. 

For more information on how to train models, check out [this tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md).
