### ISSUE TITLE
Getting detailed POS tags

### ISSUE THREAD

**Issue by rococode** [flairNLP/flair#1349]
From what I can tell, the POS tagger generates the simpler universal dependencies dataset's tags, which are like `NOUN`, `VERB`, etc.

Is there a way to get the more detailed OntoNotes tags, e.g. `NNP`, `VBZ`, etc.?

**Comment by alanakbik** [comment]
@rococode the included POS models were trained to universal POS tags. For fine-grained POS, you could train your own models using Flair by following the steps in the tutorial. This would be the quickest way to get this if you have a GPU setup to train models. 

I can also train models here and include them with the next release since fine-grained POS tags are a feature that many people could need. However, I am still setting up my new lab (waiting for hardware orders) so it will take some time.

**Comment by rococode** [comment]
Ok, thanks for the quick reply! I'll try to train my own version then.

**Comment by alanakbik** [comment]
This was just added to master branch and will be part of the upcoming release.
