### ISSUE TITLE
Use of CamemBERT's contextualized word embeddings to do regression

### ISSUE THREAD

**Issue by jusugac1** [flairNLP/flair#1351]
A clear and concise description of what you want to know.
Hello all,

I am willing to use the contextualized word embeddings obtained from CamemBERT to train a supervised learning model to do regression. I am intending to obtain these embeddings in the same way as they are obtained to perform text classification (i.e. by only keeping the output for the [CLS] token on the last hidden layer). These embeddings will be used as the vectorized representation of a sentence. Knowing that CamemBERT is adapted to classification instead of regression, do you think this word representation may work? If not, any suggestions?

Thank you,

J.

**Comment by alanakbik** [comment]
@jusugac1 we've done some regression experiments and generally, the contextualized representations always worked pretty well so it might well work for your case. 

We did it a bit differently in that we used the (still beta) `TextRegressor` class in Flair and passed `DocumentRNNEmbeddings` to it, meaning that instead of the [CLS] token we trained an RNN to take all contextualized word embeddings and produce the vector for the sentence. 

If you use the [CLS] token instead, we'd be curious to hear about your results! What dataset will you use to evaluate?
