### ISSUE TITLE
FLAIR NER multilingual - case sensitivity issue

### ISSUE THREAD

**Issue by igormis** [flairNLP/flair#1477]
I am using following stacked embeddings:
```
embedding_types: List[TokenEmbeddings] = [
                                        
    BertEmbeddings("bert-base-multilingual-cased"),
    FlairEmbeddings('multi-forward'),
    FlairEmbeddings('multi-backward'),
]
```
in order to build the multilingual NER model.
However, I have problem with case-sentitivity:
1) Input:
`{text: "Hilary Clinton critica a tramp por su falta de apoyo para reconstruir Puerto Rico"}`
output:
```
{"entities": [
    {
      "start": 0,
      "end": 14,
      "value": "Hilary Clinton",
      "entity": "person"
    },
    {
      "start": 25,
      "end": 30,
      "value": "tramp",
      "entity": "financial_topic"
    },
    {
      "start": 70,
      "end": 81,
      "value": "Puerto Rico",
      "entity": "location"
    }
  ]
}
```

2) Input:
`{text: "HILARY CLINTON CRITICA A TRUMP POR SU FALTA DE APOYO PARA RECONSTRUIR PUERTO RICO"}`
output:
```
{"entities": [
    {
      "start": 0,
      "end": 81,
      "value": "HILARY CLINTON CRITICA A TRUMP POR SU FALTA DE APOYO PARA RECONSTRUIR PUERTO RICO",
      "entity": "company"
    }
  ]
}
```
Any help how to tackle this problem? I can convert the text into small letter, but sometimes I need the text in the capital letters...

**Comment by alanakbik** [comment]
@igormis generally, capitalization is a useful feature so its best not to lowercase everything and it is normal that models that use cased embeddings give different results depending on capitalization. You could try using one of the bert uncased models instead, together with the Flair embeddings you're currently using. It might give better results (Flair embeddings are trained with random casechange so should be resilient to this and bert uncased might be more stable in this scenario). 

A potentially better approach wold be to keep the same embeddings you're using now and add uppercased (and maybe lowercased) versions of all sentences to your training data so that the model learns during training that sentences could be in all caps. This would extend your training data but potentially make the resulting model more robust.

**Comment by igormis** [comment]
Perfect, I had the last approach on my mind. Thank u for the confirmation
