### ISSUE TITLE
Custom Metric or Result

### ISSUE THREAD

**Issue by djstrong** [flairNLP/flair#1484]
To be removed, once it is done: Please add the appropriate label to this ticket, e.g. feature or enhancement.

**Is your feature/enhancement request related to a problem? Please describe.**
There are different objectives in training models. Now for early stopping (and e.g. logging) micro F1 is used. Personally, I need binary F1.

How to implement it? Maybe add method `main_score()` to `Metric` and implement own Metric with overridden this method and pass new `Metric` class to models init?
```
            result = Result(
                main_score=metric.main_score(),
                log_line=f"{metric.precision()}\t{metric.recall()}\t{metric.micro_avg_f_score()}",
                log_header="PRECISION\tRECALL\tF1",
                detailed_results=detailed_result,
            )
```
Or implement own model with overridden `evaluate`? This approach is simpler and does not need changes in flair.

**Comment by alanakbik** [comment]
Hello @djstrong good point, we'd generally like to give more control over evaluation metrics and early stopping to users, though I am also not sure what the best approach would be. 

Of the two options, I like the custom `Metric` class a bit more since this would allow it to be reused for different model types such as `SequenceTagger` and `TextClassifier` (maybe binary F1 for instance is useful for different model types). Alternatively, the existing Metric class could be extended to produce all sorts of evaluation measures (including binary F1) and the trainer then needs to only be told which metric to use in the constructor.
