### ISSUE TITLE
Building a spell correction model using Language Model

### ISSUE THREAD

**Issue by Wickky** [flairNLP/flair#1575]
Can we build a spell correction model based on a char level language model from flair?
Can anyone help me answer this? 
Thanks in advance.

**Comment by rash150996** [comment]
A language model is the one where given an input sentence, the model outputs a probability of how correct that sentence is. So the character level LM will give you how correct your word is, which is why you better create your own data and train the flair model with your own dataset. If you need any insight as to how to build a spell checker, head over to my repo for a basic version.

**Comment by Wickky** [comment]
@rash150996  Thank you for your suggestion. Can I use lm.pt instead of bin file to build a spell checker?

**Comment by rash150996** [comment]
@Wickky you're welcome. Well, I used .bin file extension for pickle dump to save my training words as it was 2.5gb and every time I needed to run the model I could just load the file rather than retraining. Since you will be using PyTorch, saving the model using .pt would make sense. It is not about the extension, it is about the quality of data in the lm.pt file and if that is what you need.

**Comment by Wickky** [comment]
Actually I haven't solved this yet! Can anyone help me building a spell checker using a character level language model?

**Comment by alanakbik** [comment]
Spell correction / checking is not a feature of Flair currently, so you would need to build an approach for this. Character language models could be a component because they can calculate the perplexity of a string. If the perplexity is lower, it more conforms to the distributions expected by the model. 

For instance, check this code:

```python
# get a language model
language_model = FlairEmbeddings('news-forward').lm

# calculate perplexity
sentence_ungrammatical = "The grass are green"
perplexity = language_model.calculate_perplexity(sentence_ungrammatical)
print(f'The sentence "{sentence_ungrammatical}" has a perplexity of: {perplexity}')

sentence_grammatical = "The grass is green"
perplexity = language_model.calculate_perplexity(sentence_grammatical)
print(f'The sentence "{sentence_grammatical}" has a perplexity of: {perplexity}')
```

It will print a lower perplexity for "The grass is green" than "The grass are green". 

However, that's only one part. How exactly to build a spell corrector on top of this I am not certain. I'd be happy to hear about your results.

**Comment by Wickky** [comment]
Actually I am stuck here. 
Let's say incorrect tokens are detected with higher perplexity.
Is there any ways to get corrected tokens or maybe a suggestions list at least?
Or maybe can we get similar vectors from incorrect token embeddings?
