### ISSUE TITLE
Language Model producing <unk> tags

### ISSUE THREAD

**Issue by Wickky** [flairNLP/flair#1576]
I have trained a char-level language model and it produces "unk" while doing prediction.

**Comment by rash150996** [comment]
What is it that you are predicting? Because sometimes when your LM is trained at the character level, it fragments the words at different syllables, which is why <UNK> token appears which either means your LM is not trained keeping your output in mind, or whatever input you are feeding into the model is has to be changed. I have worked with flair over 2 languages.

**Comment by Wickky** [comment]
@ I solved this by building my own char mappings as mentioned in [https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md#non-latin-alphabets](url) before training language model.
