### ISSUE TITLE
short conversation data for language model

### ISSUE THREAD

**Issue by Michael95-m** [flairNLP/flair#1592]
I have got some questions for how to train flair character language model from scratch.
1. I have got 10 million lines of short conversation data which are unlike formal data from wikipedia. I think many people starts training with large tons of formal data from both wikipedia and news and then continue fine tuning with informal data. My question is that is it OK to start training with conversation data which has got many spelling errors(not formal data)?? 
2. In my data, there are many english words like name (currently what I want to train is not english) and emoji. Should I remove these english words and emoji??
3. Thirdly, Is 10 million lines of short conversation data (1.2GB) not enough for scratch training?? If not, how much data should I collect more??
4. Finally, I read it that no tokenization is needed for character language model. If I don't tokenize the text data, are there any effects to the quality of the language model??

**Comment by alanakbik** [comment]
Hello @Michael95-m that is all fine, since its a character language model you don't need to worry about spelling errors or tokenization. You can use the data as it is, so you don't need to remove emoji or anything. 10 million conversations is not bad, that should be enough to train a LM.

If your data is in another language, you might need to compute [your own character dictionary first](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md#non-latin-alphabets).

Also, I would recommend using the current master branch of Flair so that you can put in custom separator tokens between each conversation. So if you have big text files with all conversations, you could put in a line with "[SEP]" (or whatever you want) between each conversation to clearly mark their boundaries. See #1541 for more info.

**Comment by Michael95-m** [comment]
Hello @alanakbik , thanks for your answers and recommendation. By the way, can I ask one more question? Can I applied the trained flair character language models for **spell correction** and checking?? If it can be applied, **how** can I do that??

**Comment by alanakbik** [comment]
Spell correction / checking is not a feature of Flair currently, so you would need to build an approach for this. Character language models could be a component because they can calculate the perplexity of a string. If the perplexity is lower, it more conforms to the distributions expected by the model. 

For instance, check this code:

```python
# get a language model
language_model = FlairEmbeddings('news-forward').lm

# calculate perplexity
sentence_ungrammatical = "The grass are green"
perplexity = language_model.calculate_perplexity(sentence_ungrammatical)
print(f'The sentence "{sentence_ungrammatical}" has a perplexity of: {perplexity}')

sentence_grammatical = "The grass is green"
perplexity = language_model.calculate_perplexity(sentence_grammatical)
print(f'The sentence "{sentence_grammatical}" has a perplexity of: {perplexity}')
```

It will print a lower perplexity for "The grass is green" than "The grass are green". 

However, that's only one part. How exactly to build a spell corrector on top of this I am not certain. I'd be happy to hear about your results.

**Comment by Michael95-m** [comment]
Thanks for your explanation @alanakbik . Btw, for the case of building flair language model, the data I have also contains keyboard typed data. When I explored the data, there are many typing errors. Is it Ok to train with that data? Previously, you mentioned that containing spelling error is ok. So I think for the case of typing errors, these typing error can't affect the quality of language model. Am I right??

**Comment by alanakbik** [comment]
Generally the models are robust, so you can train them with typing errors in your data. But these models will then work best if the data you apply them to also has such errors.

**Comment by Michael95-m** [comment]
Thank you for your explanation @alanakbik.
