### ISSUE TITLE
Update documentation for 0.5 release

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1626]
This issue tracks the progress in updating our documentation for the upcoming release.

**Comment by stefan-it** [comment]
With the new `TransformerWordEmbeddings` implementation we could also remove the old test cases: https://github.com/flairNLP/flair/blob/master/tests/test_transformer_embeddings.py, because it uses the old implementations.

And I think we can savely upgrade Transformers to the latest 2.9 version here:

https://github.com/flairNLP/flair/blob/72f4ad6706d0d4efc8711f007eeb7e2bad5a69d6/requirements.txt#L13

**Comment by alanakbik** [comment]
Good point - will do!

**Comment by alanakbik** [comment]
Flair 0.5 released
