### ISSUE TITLE
Is it case sensitive?

### ISSUE THREAD

**Issue by dwy904** [flairNLP/flair#1632]
I tried 
```
I love New York
```
and
```
i love new york
```
Only the capitalized one found NER but nothing was found in the non-capitalized sentence even the semantics is the same.

**Comment by djstrong** [comment]
You can train a model on lower letter texts.

**Comment by dwy904** [comment]
I was planning to use the pre-trained fashion NLP model for NER to save time.
https://research.zalando.com/welcome/mission/research-projects/flair-nlp/

**Comment by alanakbik** [comment]
This model unfortunately is not distributed since it was trained using proprietary data. For standard NER you could use an existing dataset like CoNLL-03 and like @djstrong wrote you could lowercase all text and then train a model for your use case that would be better able to deal with lowercased data.

**Comment by dwy904** [comment]
Thank you!
