### ISSUE TITLE
Can we fine-tune the PooledFlairEmbeddings? 

### ISSUE THREAD

**Issue by brickee** [flairNLP/flair#1633]
I want to fine-tune the pooled version of Flair and this is the code I want to use: 

PooledFlairEmbeddings('pubmed-forward',pooling =  "min",fine_tune=True,chars_per_chunk = 512)

But it does not work. How can I fine-tune the PooledFlarEmbeddings? Thanks.

**Comment by alanakbik** [comment]
That unfortunately is not possible since the pooling is over past embeddings. Allowing fine-tuning here would mean that all past embeddings would also need to be fine-tuned, which for memory reasons is not possible. Generally though, we find that fine-tuning is not beneficial for Flair embeddings, so there's a good chance it's better to do it without.
