### ISSUE TITLE
Pre-trained NER using PooledFlairEmbeddings

### ISSUE THREAD

**Issue by matteo-grella** [flairNLP/flair#1635]
I have not seen pre-trained models for NER that use the PooledFlairEmbeddings. Could you share the English model? Sorry, I missed something!

**Comment by alanakbik** [comment]
Hi @matteo-grella we currently do not distribute pre-trained NER models with pooled embeddings, since they have high memory requirements during prediction. For most use cases, it is much better to use the standard models since they are almost as accurate and require much less memory.

**Comment by matteo-grella** [comment]
Hi @alanakbik,

Thank you for your answer.

From your paper, I understood that the models would be made available to the community for reproduction. That's why I desperately searched for them before writing here:)

Since the pooled embeddings technique uses a dynamic memory that grows throughout execution, I understand high memory usage, making them not practical.

I would still ask you to make the pre-trained model available, if possible. I would love to import it on the fly into the library I am developing, [spaGO](https://github.com/nlpodyssey/spago), so that I can quickly evaluate my implementation of [pooled embeddings](https://github.com/nlpodyssey/spago/blob/master/pkg/nlp/evolvingembeddings/evolvingembeddings.go).
spaGO only works on CPU for now... That's why I would rather not train the NER model from scratch.

I have already successfully imported the `en-ner-conll03-v0.4.pt` and `en-ner-fast-conll03-v0.4.pt` models. By the way, in the [README](https://github.com/nlpodyssey/spago/blob/master/README.md) there are instructions to start a NER server with Flair models :)

**Technical note**
In spaGO, I implemented the pooled embeddings using a key-value store. This helps not always keep all values in RAM. Why not implement the same in Flair?

Thanks!

**Comment by alanakbik** [comment]
Hello @matteo-grella sorry for the late reply. Do you still require the models? If so, I could re-train and share them with you. 

Wrt to the key-value store that would be great. I tried some a long while back but they always slowed down training too much due to disk reads. Is your key-value solution working fast enough?

**Comment by matteo-grella** [comment]
Hi @alanakbik, thanks for your reply!

Yes, I'd love to make your "pooled" model available in [spaGO](https://github.com/nlpodyssey/spago/) :)

Given the weight of the calculations, I found the price of using a key-value DB acceptable. It must also be said that the [database](https://github.com/dgraph-io/badger) I found for Go is also particularly performing.

Best,

Matteo

**Comment by alanakbik** [comment]
OK great, I'll train a model and let you know once its done!

**Comment by matteo-grella** [comment]
Hey @alanakbik, do you have any update? Thanks!

**Comment by alanakbik** [comment]
Oops yes this was added in the last Flair version, I just forgot to mention it here! Sorry :D 

You can load with 
```python
tagger = SequenceTagger.load('ner-pooled')
```

Te main difference is that the pooled embeddings can handle underspecified words better if they appear somewhere else in a better context. For instance the word "Blargl" in the sentences "There is Blargl." and "George Blargl" - only the second sentence makes clear that this word is a last name. 

So if you compare the standard NER tagger with the pooled version, you see that only the pooled version can handle this sentence: 

```python
# difficult sentence
sentence = Sentence('There is Blargl. George Blargl .')

# standard NER tagger
tagger = SequenceTagger.load('ner')

# predict and print
tagger.predict(sentence)
print(sentence)

# pooled NER tagger
tagger = SequenceTagger.load('ner-pooled')

# predict and print
tagger.predict(sentence)
print(sentence)
```

However, this comes at a cost of drastically increased RAM usage, which is why we generally recommend using the standard models.

**Comment by matteo-grella** [comment]
Perfect and thanks. I'll let you know if I manage to import the model into spaGO and if the key-value store solution works in this case.

**Comment by alanakbik** [comment]
model was added, so closing issue
