### ISSUE TITLE
Why does DocumentPoolEmbeddings(..., fine_tune_mode='nonlinear) add randomness?

### ISSUE THREAD

**Issue by RouvenG** [flairNLP/flair#1645]
Why is a _default initialised (thus random)_ `torch.nn.Linear` layer added when I use `fine_tune_mode='nonlinear'`?

### Further Details:
When I use the parameter `fine_tune_mode='nonlinear'` in `DocumentPoolEmbeddings` a Non-linearity (ReLU) is added as well as a `torch.nn.Linear` layer.
If I am not wrong, the weights of the linear layer of torch are initialised randomly with a scaled uniform distribution. This means that the embeddings become partly random for each newly initiated `DocumentPoolEmbeddings`.

Can somebody please explain me why is layer is introduced.
- Does this randomness improve the embedding in any way?
- Is this layer supposed to be trained?
- If yes and I don't train is it harmful to the embedding?

I used this option because in the documentation of flair, it said:
> The default operation is 'linear' transformation, but if you only use simple word embeddings that are not task-trained you should probably use a 'nonlinear' transformation instead:

### Code Reference:
https://github.com/flairNLP/flair/blob/63aeabf9a18bdf53af3bcba5bd80f43ac717656e/flair/embeddings/document.py#L198

**Comment by alanakbik** [comment]
Hello @RouvenG yes with this initialization the embeddings are intended to be trained and will not make sense unless you do. They are trained automatically if you use them to train a model in Flair.

If you need document embeddings that do not require training (for instance because you just want to have an embedding vector for text), then you should set `fine_tune_mode='none'`. I think it might be best to set 'none' as default option for these embeddings in the future as otherwise it might be confusing.

**Comment by RouvenG** [comment]
Thank you for the support, it clarified my issue. I suggest to notify the user somehow about this behavior is not fully obvious to the user.  A hint in the documentation should be enough, for me at least.
