### ISSUE TITLE
Getting always same number of TN and TP for multilabel classification

### ISSUE THREAD

**Issue by bichomartiano** [flairNLP/flair#1663]
Hi! I would like to share a concern I'm having with the results of the models I'm training using FLAIR. I couldn't find an issue with a similar topic, forgive me if it's something already solved. It's as simple as: Im always getting same number of True positives cases for every tag in multilable text classification. This happens with CONLL02 corpus but also for every label in my own corpus (with 42 tags, so little chance that is simple casuality). Here is an example in the results of what I mean:

MICRO_AVG: acc 0.6523 - f1-score 0.7895
MACRO_AVG: acc 0.6155 - f1-score 0.7372000000000001
LOC        **tp: 94** - fp: 25 - fn: 29 - **tn: 94 -** precision: 0.7899 - recall: 0.7642 - accuracy: 0.6351 - f1-score: 0.7768
MISC       **tp: 13** - fp: 12 - fn: 20 - **tn: 13** - precision: 0.5200 - recall: 0.3939 - accuracy: 0.2889 - f1-score: 0.4483
ORG        **tp: 112** - fp: 41 - fn: 26 - **tn: 112** - precision: 0.7320 - recall: 0.8116 - accuracy: 0.6257 - f1-score: 0.7697
PER        **tp: 83** - fp: 5 - fn: 3 - **tn: 83** - precision: 0.9432 - recall: 0.9651 - accuracy: 0.9121 - f1-score: 0.9540

if these values are wrong for some reason, there fore the metrics will be wrong as well.

I'd really appreciate some insight of what might be going on here. 

Thanks a lot in advance!!

**Comment by alanakbik** [comment]
Hello @bichomartiano thanks for pointing this out! For the NER use case, true negatives cannot easily be counted which is why papers only report precision, recall and F1 which do not require TNs. Our evaluation code in the `SequenceTagger` is used for NER but also other tasks such as POS where TNs can be counted. So the current output unfortunately is confusing - we should only output TNs for non-NER tasks. 

I'll merge a refactoring of the evaluation routines that fixes this (#1671). In the new version, TNs are only counted and printed for non-NER tasks. Additionally, the PR switches to sklearn evaluation routines for most tasks and outputs an evaluation file for NER tasks so that you can also use the official conlleval script to double-check the evaluation produced by Flair.

**Comment by bichomartiano** [comment]
Okay! I understand, thank you very much for your explanation. Actually, as you pointed out, TN are not really used for F1, accuracy and precission which is what matters in the end, so it's not a true problem.

Cheers!
