### ISSUE TITLE
French language models for financial domains

### ISSUE THREAD

**Issue by sinaahmadi** [flairNLP/flair#1714]
Hi,

Thanks for this framework. 

I am not sure if you have a specific repository where you keep track of the tools and resources which are built using Flair. I would like to inform interested people on our French language models trained on uniquely financial documents using Flair. The language models and the resources can be found at [https://github.com/CoFiF/Corpus](https://github.com/CoFiF/Corpus).

Thanks.

**Comment by alanakbik** [comment]
Hello @sinaahmadi thanks for letting us know! The work looks interesting and will surely be useful to many people. We don't yet have a place where we keep track of this information (we probably need one), but we try to integrate most open resources directly into Flair. 

Would you be interested in putting in a PR so that your models are directly available through Flair? You would need to add your models to the method here: https://github.com/flairNLP/flair/blob/1732885cad5584d7067ed290f779d8a7bc347cba/flair/embeddings/token.py#L431

**Comment by sinaahmadi** [comment]
@alanakbik Thanks for your suggestion. 

If there is a mechanism to recognize the language model, I would be happy to put in a pull request. The work is based on a paper and it matters to us that it'll be cited accordingly in the future. If no, do you think it'd be possible to have an extra page in your wiki to link to relevant projects?

**Comment by alanakbik** [comment]
Yes I can understand that! We currently link to the contributors in the documentation (for example [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md#german-models)), but additionally we should create a documentation page for all the contributions and the proper ways to cite them. I'll think about how to best do it. Do you think a single page with a list would do it that is referred to on the title page?

**Comment by sinaahmadi** [comment]
Yeah, a single page with tables for different tasks, like the one you linked to, would be nice. That way, the page will get updated instead of hard coding.
