### ISSUE TITLE
Flair prediction speed and allowed maximum number of tags of predicted sentences

### ISSUE THREAD

**Issue by Michael95-m** [flairNLP/flair#1756]
I'd like to ask a few questions about flair embedding. 

- First, I'd like to know is there any options about **increasing prediction speed** of the model that uses **flair embedding**. I've trained the POS model with stacked embedding of flair embedding(with hidden state of 2048) and word embedding and the result is pretty good. But the drawback is that it takes **2 or 3** seconds for **normal** sentence and takes **longer** when predicting **longer** sentences. I saw some answers like prediction with **batch processing** and **sentence breaking** but for the language I've trained, sentence breaking is not simple as Latin based languages and prediction with batch processing makes faster(between 15 and 25 sentences per second) but I need more speed. Are there any options about increasing prediction speed of the model that uses flair embedding besides retrained flair embedding with lower hidden states??
- Second, before I use flair, I used to train the POS model with scratch training. At that time, I needed to set maximum allowed tags during training and during prediction, my scratch trained model can't predict the sentences with more than maximum allowed tags. When I started to use and train models in flair framework, what I found out that I don't need to care about the **maximum** allowed tags in prediction(besides transformer model. In the transformer model  it can only predict  maximum 512 tags of sentence). I mean mdoels trained using flair framework can predict the **unlimited** number of tags in sentence. What I'd like to know is that how the models from flair framework can handle unlimited number of tags??

**Comment by alanakbik** [comment]
Hi @Michael95-m: 

- Batch processing is the best way to increase speed. You could give lists of 1000 sentences to the `predict()` method at the same time and then set the `mini_batch_size` as high as your memory allows (I like to set 32 or 64). This will cause the predict method to batch sentences of similar length together for speedup. Of course, the best way to get good speed is using a GPU. Another option is to use smaller Flair embeddings with 1024 states which for POS tagging is normally enough. For English, we ship the `news-forward-fast` and `news-backward-fast` embeddings which are smaller. This should give a big speed-up. 

- Yes Flair models can predict for sentences of unlimited length. That's because the Flair embeddings are RNN-based which can handle sequences of arbitrary length. RNNs go through a sentence word by word and update a hidden state, so they do not need to see the entire sentences at once. The transformer-based embeddings can as of Flair 0.5.1 also handle sentences of unlimited length if you set `allow_long_sentences=True` when you initialize them.

**Comment by Michael95-m** [comment]
@alanakbik , thanks for your kind answers.
