### ISSUE TITLE
Arabic LM

### ISSUE THREAD

**Issue by Yugioh1984** [flairNLP/flair#179]
Hello,
I tried to generate a Language model for Arabic using Flair, but it seems not working as expected. I used the Leipzig Corpora Collection as my training corpus. It contains 1M sentences in Arabic. Here is the code used for the training:
###############
language_model = LanguageModel(dictionary,
                               is_forward_lm,
                               hidden_size=512,
                               nlayers=1)

# train your language model
trainer = LanguageModelTrainer(language_model, corpus)

trainer.train('resources/taggers/language_model',
              sequence_length=250,
              mini_batch_size=100,
              max_epochs=10)
##############
Once finished, when I try to generate text via the script provided with Flair, I got this display:
![text generation arabic](https://user-images.githubusercontent.com/38903939/47649706-5d270280-db7e-11e8-822b-caae8fcc2766.png)

Should I preprocess my dataset before the training or It's just an underfitting issue?
Please advice on this?

**Comment by alanakbik** [comment]
Hello @Yugioh1984 that's great - I think a character-based approach would probably work very well for Arabic, so we'd be very interested in hearing your results! 

The problem in your code is that you're using the default dictionary that gets loaded with:

```python
# load the default character dictionary
dictionary = Dictionary.load('chars')
```
This default dictionary contains the most common chars calculated over some corpora that do not include much Arabic - this means that most if not all Arabic letters are not part of the dictionary and thus get "unk'ed", i.e. replaced with the "unk" symbol. 

To address this, you must first compute your own dictionary that includes the Arabic alphabet. Here is a code snippet that we used to get the most common characters out of a corpus: 

```python

# make an empty character dictionary
from flair.data import Dictionary
char_dictionary: Dictionary = Dictionary()

# counter object
import collections
counter = collections.Counter()

processed = 0

import glob
files = glob.glob('/path/to/your/corpus/files/*.*')

print(files)
for file in files:
    print(file)

    with open(file, 'r', encoding='utf-8') as f:
        tokens = 0
        for line in f:

            processed += 1            
            chars = list(line)
            tokens += len(chars)

            # Add chars to the dictionary
            counter.update(chars)

            # comment this line in to speed things up (if the corpus is too large)
            # if tokens > 50000000: break

    # break

total_count = 0
for letter, count in counter.most_common():
    total_count += count

print(total_count)
print(processed)

sum = 0
idx = 0
for letter, count in counter.most_common():
    sum += count
    percentile = (sum / total_count)

    # comment this line in to use only top X percentile of chars, otherwise filter later
    # if percentile < 0.00001: break

    char_dictionary.add_item(letter)
    idx += 1
    print('%d\t%s\t%7d\t%7d\t%f' % (idx, letter, count, sum, percentile))

print(char_dictionary.item2idx)

import pickle
with open('/path/to/your_char_mappings', 'wb') as f:
    mappings = {
        'idx2item': char_dictionary.idx2item,
        'item2idx': char_dictionary.item2idx
    }
    pickle.dump(mappings, f)
```

You can then use this dictionary instead of the default one in your code for training the language model: 

```python
import pickle
dictionary = Dictionary.load_from_file('/path/to/your_char_mappings')
```

Does this work for you? (Test first on small data before training a large LM)

**Comment by Yugioh1984** [comment]
Hello @alanakbik. Thx a lot for the code snippet. I did a test and it works 👍 . Here is the text generated :
![lm_text_ar](https://user-images.githubusercontent.com/38903939/47848500-ca30d700-ddce-11e8-8579-26335a6d200f.png)

I will try to use a bigger corpus and see the outcome.
By the way, concerning the train/dev/test split, is there an optimal split or I can just choose a standard split like 80/10/10?

**Comment by alanakbik** [comment]
Hey looks great! We typically do something like 80/10/10, though if you have a very large corpus you could do even smaller text/dev splits to speed things up. 

Please keep us posted on your results! What tasks will you apply it on?

**Comment by Yugioh1984** [comment]
Currently, I'm working on Arabic NER then I will try to work also on other sequence labeling tasks for Arabic.
I'm using 16 cores CPU right now for the training. Once I got my GPU I will try bigger NN and corpora. I will update you with the progress asap.

**Comment by alanakbik** [comment]
Just a quick heads up: we've just pushed an update into master that includes pre-trained FastText embeddings for Arabic. You can load them with: 

```python
embeddings = WordEmbeddings('ar')
```
For now only available through master branch, but we're planning another version release (0.3.2) in a few days - then they'll also be available if you install from pip.

**Comment by alanakbik** [comment]
Hi @Yugioh1984 any news on this? We're collecting models for the next flair release and were wondering if you had some Arabic models already trained that you would be willing to share?

**Comment by Yugioh1984** [comment]
Hi @alanakbik , I'm still waiting for my GPU but in the meantime I'm running an Arabic LM with 512 HS on my CPU. As you may expect it's a bit slow. I will let you with the progress asap. By the way, how many epochs I should run my model: 50, 100 or less?

**Comment by Yugioh1984** [comment]
Hi @alanakbik , I finally was able to start training the Arabic LM but It seems that it's not working as expected. The learning rate has annealed very quickly (63min) from 20 to 5. Then after 4h50min the learning rate was equal to zero. Please find in attachment my training log.
Should I restart my training using bigger learning rate / patience? Please advice on this?
[training.log](https://github.com/zalandoresearch/flair/files/2716726/training.log)

**Comment by alanakbik** [comment]
Hi @Yugioh1984 - great to hear about your progress! 

Yes the learning rate anneals too quickly. This is likely because your dataset is quiet small and you have many training splits. As you can see in the logs, each training split only takes about 10 seconds (normally, we target about 20 minutes per split). 

Because the `patience` looks at the number of splits without improvement and you have many very small splits, the learning rate anneals too fast. 

You have two options: 
- Increase the dataset size by one to two orders of magnitude. Try to get at least 100 million Arabic sentences in your dataset. For instance, OpenSubtitles 2018 has some [35 million Arabic sentences](http://opus.nlpl.eu/download.php?f=OpenSubtitles2018%2Fmono%2FOpenSubtitles2018.raw.ar.gz) and  MultiUN has over [10 million Arabic sentences](http://opus.nlpl.eu/download.php?f=OpenSubtitles2018%2Fmono%2FOpenSubtitles2018.raw.ar.gz). There are probably lots of other good Arabic datasets out there.
- Decrease the number of splits so that each split takes much longer to process. With the small dataset you have right now, you could try lowering to 5 splits. If you add the datasets above, you can try 50 splits. 

If possible, try the above two options in combination to train a larger LM. 

Hope this helps!

**Comment by fatimabs** [comment]
> Hello,
> I tried to generate a Language model for Arabic using Flair, but it seems not working as expected. I used the Leipzig Corpora Collection as my training corpus. It contains 1M sentences in Arabic. Here is the code used for the training:
> ###############
> language_model = LanguageModel(dictionary,
> is_forward_lm,
> hidden_size=512,
> nlayers=1)
> # train your language model
> 
> trainer = LanguageModelTrainer(language_model, corpus)
> 
> trainer.train('resources/taggers/language_model',
> sequence_length=250,
> mini_batch_size=100,
> max_epochs=10)
> ##############
> Once finished, when I try to generate text via the script provided with Flair, I got this display:
> ![text generation arabic](https://user-images.githubusercontent.com/38903939/47649706-5d270280-db7e-11e8-822b-caae8fcc2766.png)
> 
> Should I preprocess my dataset before the training or It's just an underfitting issue?
> Please advice on this?

I'm a phd student from Tunisia, PLZ can you help to build a flair embedding model using my own data  ?

**Comment by Yugioh1984** [comment]
@fatimabs: you need to generate an Arabic character dictionary to be able to get relevant results. You can use the code provided in the documentation: https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md.
Have a look also at the first comments of this issue for more details.

**Comment by fatimabs** [comment]
@Yugioh1984 can i PLZ have your contact (email) ?

**Comment by zeeshansayyed** [comment]
@fatimabs 
I am also trying to train an Arabic LM. I can share my progress once I am successfully able to do so. As far as your questions are concerned:

1. test.txt and valid.txt are your typical ML test/validation split. I think learning rate slow down and stopping are based on valid, whereas test is there to purely evaluate your LM.
2. So that it fits in your GPU memory easily. 
3. You can if you have a GPU. But from what has been written in the tutorial, it would take about a week with a good GPU for a 1 billion word corpus.

**Comment by fatimabs** [comment]
@zeeshansayyed i'm also trying to train an Arabic model with  lair embeddings but i have a problem when i download the corpus :orpus = TextCorpus(Path('/content/drive/My Drive/arabic_corpus'),
dictionary,
is_forward_lm,
random_case_flip=False,
character_level=True)

UnicodeDecodeError Traceback (most recent call last)

in ()
6 is_forward_lm,
7 random_case_flip=False,
----> 8 character_level=True)

3 frames

/usr/lib/python3.6/codecs.py in decode(self, input, final)
319 # decode input (taking the buffer into account)
320 data = self.buffer + input
--> 321 (result, consumed) = self._buffer_decode(data, self.errors, final)
322 # keep undecoded input until the next call
323 self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

have you any idea how can i resolve the bug?

**Comment by alanakbik** [comment]
This looks like an encoding error - can you make sure that your files are UTF-8 encoded? Could you try with a different file to see if it works?

**Comment by fatimabs** [comment]
@alanakbik thanks a lot , i resolve th problem, PLZ how can i use flair embeddings to calculate similarity between 2 sentences ?

**Comment by stefan-it** [comment]
@fatimabs Just have a look at this post from @alanakbik:

https://github.com/zalandoresearch/flair/issues/321#issuecomment-492577922

It shows how to calculate similarities between two sentences.

Anyway, feel also free to test my trained language model for Arabic:

https://github.com/zalandoresearch/flair/issues/614 :)

**Comment by fatimabs** [comment]
@stefan-it 

Thanks for the response, but i have a question PLZ
To train my own model, i must have a labeled data or only a corpus of text ?
what is the difference between test.txt and valid.txt? and what  test.txt and valid.txt should contain?

**Comment by zeeshansayyed** [comment]
@fatimabs You do not need labeled data for learning the language model. You would need annotated data for the specific downstream task for which you will use the embeddings learned from the language model. The validation and test sets are just subsets of the corpus to make sure that you are not overfitting the language model.

A good primary post for learning about character level language models is [this](http://karpathy.github.io/2015/05/21/rnn-effectiveness/).

**Comment by fatimabs** [comment]
@zeeshasayyed thanks a lot
What about the size of validation.txt ans test.txt?

**Comment by zeeshansayyed** [comment]
So ideally an 80:10:10 train: valid: test split would be good. But I am training on a huge corpus of more than 1.5B words. So I am just using 2.5% data in validation and test sets both. This leaves 95% of the corpus which I am further splitting into 100 parts.

Another thing which you would want to do on the corpus is some minimal preprocessing, like removing the Tashkeel and so on.

**Comment by fatimabs** [comment]
Dear @zeeshansayyed  i'm very grateful
i have juste another question, when i want to compare two sentences this line: 
`# first, declare how you want to embed
embeddings = DocumentPoolEmbeddings(
    [WordEmbeddings('glove'), FlairEmbeddings('news-forward'), FlairEmbeddings('news-backward')])`

should be changed for Arabic language ?

**Comment by zeeshansayyed** [comment]
@fatimabs There aren't any flair embeddings for Arabic present at the moment. But I think there are FastText embeddings for Arabic which can be loaded as:
`arabic_embeddings = WordEmbeddings('ar')`

Also, you can load the embeddings from your own trained language model as:
`char_lm_embeddings = FlairEmbeddings('resources/taggers/language_model/best-lm.pt')`

You can combine these to together in order to use for your sentence similarity experiments.

You can also test the model uploaded by @stefan-it in #614 while you wait for your embeddings to be trained.

**Comment by fatimabs** [comment]
@zeeshansayyed  my own model is trained using skip gram tool , can i so use it ?

**Comment by atif-zakaria** [comment]
@fatimabs can you give me more details about your model plz

**Comment by abeermohamed1** [comment]
Hi @alanakbik Please in the below code how to use my created Arabic dictionary. thank you for your continuous support.

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='dev.txt')
    

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

# initialize embeddings
embedding_types: List[TokenEmbeddings] = [

    # GloVe embeddings
    WordEmbeddings('ar'),

    # contextual string embeddings, forward
    PooledFlairEmbeddings('ar-forward', pooling='min'),

    # contextual string embeddings, backward
    PooledFlairEmbeddings('ar-backward', pooling='min'),
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type)

# initialize trainer
from flair.trainers import ModelTrainer
trainer: ModelTrainer = ModelTrainer(tagger, corpus)

checkpoint = '/content/gdrive/My Drive/resources/taggers/example-ner/checkpoint.pt'
from pathlib import Path
trainer = ModelTrainer.load_checkpoint(checkpoint, corpus)

trainer.train('/content/gdrive/My Drive/resources/taggers/example-ner',
              train_with_dev=True,  
              max_epochs=120,checkpoint=True)

**Comment by abeermohamed1** [comment]
> Hello @Yugioh1984 that's great - I think a character-based approach would probably work very well for Arabic, so we'd be very interested in hearing your results!
> 
> The problem in your code is that you're using the default dictionary that gets loaded with:
> 
> ```python
> # load the default character dictionary
> dictionary = Dictionary.load('chars')
> ```
> 
> This default dictionary contains the most common chars calculated over some corpora that do not include much Arabic - this means that most if not all Arabic letters are not part of the dictionary and thus get "unk'ed", i.e. replaced with the "unk" symbol.
> 
> To address this, you must first compute your own dictionary that includes the Arabic alphabet. Here is a code snippet that we used to get the most common characters out of a corpus:
> 
> ```python
> # make an empty character dictionary
> from flair.data import Dictionary
> char_dictionary: Dictionary = Dictionary()
> 
> # counter object
> import collections
> counter = collections.Counter()
> 
> processed = 0
> 
> import glob
> files = glob.glob('/path/to/your/corpus/files/*.*')
> 
> print(files)
> for file in files:
>     print(file)
> 
>     with open(file, 'r', encoding='utf-8') as f:
>         tokens = 0
>         for line in f:
> 
>             processed += 1            
>             chars = list(line)
>             tokens += len(chars)
> 
>             # Add chars to the dictionary
>             counter.update(chars)
> 
>             # comment this line in to speed things up (if the corpus is too large)
>             # if tokens > 50000000: break
> 
>     # break
> 
> total_count = 0
> for letter, count in counter.most_common():
>     total_count += count
> 
> print(total_count)
> print(processed)
> 
> sum = 0
> idx = 0
> for letter, count in counter.most_common():
>     sum += count
>     percentile = (sum / total_count)
> 
>     # comment this line in to use only top X percentile of chars, otherwise filter later
>     # if percentile < 0.00001: break
> 
>     char_dictionary.add_item(letter)
>     idx += 1
>     print('%d\t%s\t%7d\t%7d\t%f' % (idx, letter, count, sum, percentile))
> 
> print(char_dictionary.item2idx)
> 
> import pickle
> with open('/path/to/your_char_mappings', 'wb') as f:
>     mappings = {
>         'idx2item': char_dictionary.idx2item,
>         'item2idx': char_dictionary.item2idx
>     }
>     pickle.dump(mappings, f)
> ```
> 
> You can then use this dictionary instead of the default one in your code for training the language model:
> 
> ```python
> import pickle
> dictionary = Dictionary.load_from_file('/path/to/your_char_mappings')
> ```
> 
> Does this work for you? (Test first on small data before training a large LM)

Could you please let me know how to use my defined dictionary in model learning? thanks in advance.

**Comment by abeermohamed1** [comment]
Hi, I am getting the below error when use the below code
# initialize embeddings
embedding_types: List[TokenEmbeddings] = [

    # fastext embeddings
    WordEmbeddings('ar'),

    # contextual string embeddings, forward
    PooledFlairEmbeddings('ar-forward', pooling='min'),

    # contextual string embeddings, backward
    PooledFlairEmbeddings('ar-backward', pooling='min'),
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-7-d824f5f07bf7> in <module>()
     32 
     33     # GloVe embeddings
---> 34     WordEmbeddings('ar'),
     35 
     36     # contextual string embeddings, forward

3 frames
/usr/local/lib/python3.6/dist-packages/flair/embeddings.py in __init__(self, embeddings, field)
    323         else:
    324             self.precomputed_word_embeddings = gensim.models.KeyedVectors.load(
--> 325                 str(embeddings)
    326             )
    327 

/usr/local/lib/python3.6/dist-packages/gensim/models/keyedvectors.py in load(cls, fname_or_handle, **kwargs)
    210     @classmethod
    211     def load(cls, fname_or_handle, **kwargs):
--> 212         return super(BaseKeyedVectors, cls).load(fname_or_handle, **kwargs)
    213 
    214     def similarity(self, entity1, entity2):

/usr/local/lib/python3.6/dist-packages/gensim/utils.py in load(cls, fname, mmap)
    420         compress, subname = SaveLoad._adapt_by_suffix(fname)
    421 
--> 422         obj = unpickle(fname)
    423         obj._load_specials(fname, mmap, compress, subname)
    424         logger.info("loaded %s", fname)

/usr/local/lib/python3.6/dist-packages/gensim/utils.py in unpickle(fname)
   1359         # Because of loading from S3 load can't be used (missing readline in smart_open)
   1360         if sys.version_info > (3, 0):
-> 1361             return _pickle.load(f, encoding='latin1')
   1362         else:
   1363             return _pickle.loads(f.read())
