### ISSUE TITLE
Pytorch Lightning / Ray Tune - Trainer

### ISSUE THREAD

**Issue by RXminuS** [flairNLP/flair#1863]
We've written a [Pytorch-lightning](https://github.com/PyTorchLightning/pytorch-lightning) based trainer that more easily integrates with [Ray Tune](https://docs.ray.io/en/latest/tune/) ([and this](https://docs.ray.io/en/latest/tune/tutorials/tune-pytorch-lightning.html)) for hyper-parameter tuning. 

Our trainer isn't fully compatible with the existing workflow / checkpointing, because it uses PyTorch-lightning's conventions instead of Flair's own conventions. Nevertheless, we feel it might still be a powerful enough workflow to either complement / replace the existing trainer.

Just wanted to gauge interest for a PR (there's some tidying up to do on our end) and get a bit clearer picture of what constraints are seen as important in terms of interoperability with loading in previous checkpoints and outputting metrics etc?

**Comment by alanakbik** [comment]
Hi @RXminuS that sounds awesome - we've long thought about how to integrate PyTorch lightning with Flair! 

I would say the trainer constraints are mostly in terms of functionality, interoperability with checkpoints created with our standard ModelTrainer is not necessary - and since Lightning integration adds lots of features, it would be ok if not all current features can be ported over. I'm happy to take a look at a preliminary version of the PR to give feedback!

**Comment by RXminuS** [comment]
Cool, let me clean up some of our initial code. And then maybe it makes sense if we schedule a time to take a peek and then re-create a new PR based on the Lightning code. Right now it is quite tightly coupled to exactly what we needed ourselves but with the boilerplate there it's probably much easier to create a PR to port-all-the-things.

I must say that the PyTorch code in Flair is a truly examplar style for ML/PyTorch code! Super readable :-)
