### ISSUE TITLE
Sentence Augmentation (NLPAug)

### ISSUE THREAD

**Issue by RXminuS** [flairNLP/flair#1903]
We've recently integrated https://github.com/makcedward/nlpaug in our own framework and got a nice boost in validation performance / generalization. Especially for adding resilience to typo's and mis-punctation (common mistakes in our domain, but infrequent in our dataset). 

One mistake that we made is randomly sampling the augmentations on the fly rather than producing randomly augmented dataset. But suspect there might be a few more important things to consider. Would love to discuss a general architecture / integration point for adding in these augmentations. Couple of my initial questions to get started with a PR

1. Good idea? Anything existing projects / past projects we should consider?
2. Should the augmentations be for the entire dataset or per embedding (we had per dataset)? Where is the tokenization currently handled, should it be before or after?
3. Can we come up with a nice API for specifying / stacking the augmentations. I would think that something similar to how embeddings are stacked might work well?
4. Any constraints w.r.t. caching or the creation of the vocabularies that we should take into account?

**Comment by RXminuS** [comment]
Here's a simple example of what a "per embedding / tokenization" way might look like
https://gist.github.com/manishiitg/8fd4209fcb3c6cb08ed34705c1f32c86 . I'm initially leaning more towards augmenting the entire sentence during training but that might shift tag-spans too.

**Comment by makcedward** [comment]
Agree that augmenting synthetic data on the fly may not be a good approach. First of all, generation may take a long time (depends on methods) and leading a long model training time. Also, cannot reproduce the same result.

For #2, depends on use cases. If you are tacking an imbalanced dataset, augmenting the specific label of the dataset. If you are a simulating typo, targeting the whole dataset may be a good approach.

For #3: I am open to adding an interface to support (I am the owner of nlpaug)

Hope it helps

**Comment by alanakbik** [comment]
Hello @RXminuS and @makcedward really cool idea and project! 

From a quick glance I'd agree that doing it on the dataset-level makes sense - perhaps this could be added as a generic function to the `Corpus` object so that all datasets in Flair inherit this functionality. Maybe here one could add a way to stack augmentations. 

Since the augmentations are heuristics, it's probably best if augmentation does not extend to the test split of each dataset, so that we have dependable evaluation numbers.

For the vocabularies in the embeddings it actually makes no difference, since each embedding manages its own, pre-computed vocabulary. The only embedding that computes its vocabulary based on a corpus is OneHotEmbeddings which is I believe not widely used and would still be able to deal with this if we do augmentation on the `Corpus` level.

I'd be happy to take a look, though I am swamped until end next week so I could get involved after!
