### ISSUE TITLE
How to load fine tuned model to huggingface? 

### ISSUE THREAD

**Issue by samarpan-rai** [flairNLP/flair#1928]
I've fine tuned a `huggingface` model using flair for a classification task. I have it saved in a directory and and among many files, it has `final-model.pt`. I want to load this model to huggingface. How can I do this?

**Comment by stefan-it** [comment]
Hi @samarpan-rai ,

this is a very interesting question, because I'm now working on an integration of Hugging Face model hub with Flair.

For a sequence tagger model, an uploaded model (to HF model hub) can be used in Flair with this PR:

https://github.com/flairNLP/flair/pull/1974

However, it is not yet supported for text classification models, but could work on that next.

As Hugging Face is using `git-lfs` as storage, it will be awesome if you could upload your trained model under your desired namespace with a `flair` prefix, such as `hf-user-name/flair-classification-dataset-name`. That would be the repository name.

Your model should then be renamed to `model.bin` (because the `.bin` extension is already registered for lfs uploads).

Details about uploading a model with `git-lfs` are described here:

https://huggingface.co/transformers/model_sharing.html

After uploading the model, just ping me here on GitHub, then I'll do the Flair integration of the model loading :hugs:
