### ISSUE TITLE
Covert Spacy annotation to Flair BIO format (Overlap Issue)

### ISSUE THREAD

**Issue by wahid18benz** [flairNLP/flair#2010]
Hello, I'm trying to convert Spacy annotation to Flair BIO Format, I'm facing an overlapping problem between entities!
Here is and exemple of the code:

`

        import spacy

        from spacy.gold import biluo_tags_from_offsets

        nlp = spacy.load('en_core_web_sm')

        TRAIN_DATA =  [ 

        ("PRICE INCREASED EVERY 6 HOURS", {"entities": [(16, 29, "TIME"),(22, 29, "TIME")]}),
        ("DISCOUNT SALES ANNOUNCED FOR  2 TIMES DAILY", {"entities": [(30, 43, "ORG"),(38, 43, "ORG")]})

        ]

        docs = []

        for text, annot in TRAIN_DATA:

        doc = nlp(text)

        biluo = biluo_tags_from_offsets(doc, annot['entities'])

        for word,tag in zip(doc, biluo):

           print(word, tag)
`
**"Error: Trying to set conflicting doc.ents: '(16, 29, 'TIME')' and '(22, 29, 'TIME')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap."**
is there any solution for the overlapping problem ?

**Comment by whoisjones** [comment]
From spacy's [documentation](https://support.prodi.gy/t/what-happens-if-your-annotation-has-overlapping-entity-spans/363):

> The entity recognizer is constrained to predict only non-overlapping, non-nested spans. The training data should obey the same constraint. If you like, you could have two sentences with the different annotations in your data. I’m not sure whether this would hurt or help your performance, though.
If you want spaCy to learn to recover both annotations, you could have two EntityRecognizer instances in the pipeline. You would need to move the entity annotations into an extension attribute, because you don’t want the second entity recogniser to overwrite the entities set by the first one.

**Comment by wahid18benz** [comment]
Thank you @whoisjones  for your response. it's so clear to me now.
