### ISSUE TITLE
Update TransformerWordEmbeddings

### ISSUE THREAD

**Issue by schelv** [flairNLP/flair#2027]
**Is your feature/enhancement request related to a problem? Please describe.**

Currently there is this bug  https://github.com/flairNLP/flair/issues/1902
I've looked into it, and the most simple solution is to use other methods than the deprecated `encode_plus()` which produces the bug.

**Describe the solution you'd like**
My solution is to use the `__call__` method of the `PreTrainedTokenizerFast` class of the latest version of the transformers package (version 4).
It has many options that could replace a lot of the code in the current `_add_embeddings_to_sentences` method in the `TransformerWordEmbeddings` class.

For example giving already word-tokenized input, and using the [word_ids](https://huggingface.co/transformers/main_classes/tokenizer.html#transformers.BatchEncoding.word_ids) method to get a mapping from one type of token to the other.

The problem is that the current flair version uses transformers 3.
Are there plans to use the latest version?
In that case I am willing to implement these changes to the `TransformerWordEmbeddings`.

**Comment by alanakbik** [comment]
@schelv interesting - we pinned the transformers version to 3.5.1 since there were some problems with the transformers 4 release candidate that broke our unit tests involving distilbert models. Generally, I'd like to update to the newest version, but always tend to wait a few weeks to be sure things are ironed out. Perhaps in ~2 weeks we could do some testing if updating to 4 is possible.

**Comment by schelv** [comment]
All right!
Did you see there already is a 4.0.1 out?
They also made a list with changes from version 3 to 4 https://github.com/huggingface/transformers/blob/master/docs/source/migration.md

**Comment by alanakbik** [comment]
Thanks for the pointer, we should probably migrate soon!
