### ISSUE TITLE
Load customized character embeddings

### ISSUE THREAD

**Issue by KRSTD** [flairNLP/flair#2044]
Hi,

I would like to know if we can use a customized character embeddings model in the embedding layer. Similar to the below issue, however, I need to load a model that is saved as model.hdf5 type.

Please help!

Issue:Load customized embedding like sci-bert #1239

**Comment by KRSTD** [comment]
Also, is there a way I can load a file that has vectors for every character (say 96 characters in general which including 52 English letters both cases, 10 digits, 33 special characters, and new line character) and then concatenate in the stacked embeddings.

**Comment by alanakbik** [comment]
There is currently no out-of-the-box functionality for this, but you can add it fairly easily. We have the `CharacterEmbeddings` class which is for training an LSTM character model on a downstream task. If instead you want to use a CNN model, you would need to create a similar embeddings class to this one, with a CNN instead of an LSTM. You could do this by copying this class into a new class called `CNNCharacterEmbeddings` and making the appropriate changes. You can write it in such a way that it loads a pre-trained CNN if you have one.
