### ISSUE TITLE
Add options for pooling strategy in TransformerDocumentEmbeddings class

### ISSUE THREAD

**Issue by kishaloyhalder** [flairNLP/flair#2179]
**Is your feature/enhancement request related to a problem? Please describe.**
Currently the `TransformerDocumentEmbeddings` class produces the `CLS` token's encoded representation as the embedding of the input sentence. It would be great if it also provided support for other common pooling strategies such as `mean` and `max`

**Comment by allenyummy** [comment]
Hi,

When will this feature be released in the python package ? 
(Now latest version of flair is 0.8.0.post1, which doesn't support this feature.)

Also, I have an another question about "mean" and "max".
First, we could get each embeddings of {[CLS] token1, token2, .... [SEP]} from the transformer-based models.
When I dig into the code, embeddings of [CLS] and [SEP] seems to be calculated for a document embedding.
I'm curious about that. Does it make sense ?

DocumentPoolEmbeddings just takes embedding of token1, token2, ... as input to calculate a document embedding, instead of considering [CLS] and [SEP].

When we calculate "mean" by TransformerDocumentEmbeddings, should the way of calculating be the same as DocumentPoolEmbeddings ?

Thanks.

**Comment by allenyummy** [comment]
I got a experiment:

A = TransformerWordEmbeddings("ckiplab/bert-base-chinese")
B = TransformerDocumentEmbeddings("ckiplab/bert-base-chinese")
C = DocumentPoolEmbeddings([word_embedding])

1. I calculate each embeddings of token by word_embedding by A, and then calculate the mean as document embeddings.
2. I calculate document embeddings by B.
3. I calculate document embeddings by C.

A = C ≠ B

**Comment by alanakbik** [comment]
It should be part of the next release. In the meantime, you can test the feature by installing from master branch: 

~~~
pip install --upgrade git+https://github.com/zalandoresearch/flair.git 
~~~
