### ISSUE TITLE
TransformerWordEmbeddings tutorial bug

### ISSUE THREAD

**Issue by matirojasg** [flairNLP/flair#2182]
In this tutorial: https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md.

I tried the following code:

```
from flair.data import Sentence
from flair.embeddings import TransformerWordEmbeddings

sentence = Sentence('The grass is green.')

# use only last layers
embeddings = TransformerWordEmbeddings('bert-base-uncased', layers='-1')
embeddings.embed(sentence)
print(sentence[0].embedding.size())

sentence.clear_embeddings()

# use last two layers
embeddings = TransformerWordEmbeddings('bert-base-uncased', layers='-1,-2')
embeddings.embed(sentence)
print(sentence[0].embedding.size())

sentence.clear_embeddings()

# use ALL layers
embeddings = TransformerWordEmbeddings('bert-base-uncased', layers='all')
embeddings.embed(sentence)
print(sentence[0].embedding.size())
```

This should print:

torch.Size([768])
torch.Size([1536])
torch.Size([9984])

But it actually print:

torch.Size([768])
torch.Size([768])
torch.Size([768])

Why is the code not doing the concatenation?

**Comment by stefan-it** [comment]
Hi @matirojasg ,

the reason is that one parameter of the `TransformerWordEmbeddings` changed its default value. So you're using specific layers and they will be averaged (via `torch.mean`) now:

https://github.com/flairNLP/flair/blob/8b93b409ace6f93cde2f5ff88f52daca92f5a311/flair/embeddings/token.py#L791

In order to get the expected result, you need to specify `layer_mean=False`, and yes, this should be fixed in the documentation! 

Thanks for pointing it out :hugs:

**Comment by matirojasg** [comment]
Thanks 😁
