### ISSUE TITLE
there is no key  "type" in the dictionary  in the new version of flair 

### ISSUE THREAD

**Issue by nnadine25** [flairNLP/flair#2335]
i use flair to get type of named entities :

i can't find the key type, all i get when using print(sentence.to_dict(tag_type='ner')) is :

{'text': 'George Washington went to Washington.', 'labels': [], 'entities': [{'text': 'George Washington', 'start_pos': 0, 'end_pos': 17, 'labels': [PER (0.9989)]}, {'text': 'Washington', 'start_pos': 26, 'end_pos': 36, 'labels': [LOC (0.9942)]}]}

and labels contain the type but not as string format

**Comment by sachio222** [comment]
Sorry, this is not the type OP is referring to. There is a type of entity, whether it is a Person, an Organization or a Location, returned as type:PER, type: ORG or type: LOC. 

The suggestion you provided returns the data type of 'flair.data.label'.

The type that is no longer being returned in the dict is used to sort out people from places, and seems to be a bug, unless it was intentionally removed. 

In order to work around this, using your code above,

**Comment by sachio222** [comment]
As a work around, how can I do anything with the flair.data.label object?

I want to filter out people but find it rather confusing to [PER (1.0)] to grab them based on any filter or mapping

**Comment by alanakbik** [comment]
hello @sachio222 here is a snippet to get person annotations: 

```python
from flair.data import Sentence
from flair.models import SequenceTagger

# example sentence
sentence = Sentence("John Smith and Hans Müller went to Washington.")

# load NER tagger and predict
tagger = SequenceTagger.load('ner')
tagger.predict(sentence)

# iterate over predicted named entities
for entity in sentence.get_spans('ner'):

    # check if entity is a person (tagged as PER)
    if entity.tag == 'PER':

        # print the text of the entity
        print(entity.text)
```

This prints: 

```console
John Smith
Hans Müller
```
