### ISSUE TITLE
long time needs to be processed using Hunflair

### ISSUE THREAD

**Issue by minstar** [flairNLP/flair#2347]
Hi, I am using the Hunflair tool to check the latency of raw text and 
I'm not sure this is correct to process the Hunflair tool.

I followed the ReadME code to process the raw text data.
However, it took so many times (7.5 seconds per PubMed abstract).
2.2 GB memory of the GPU is allocated to the Hunflair.

**Comment by mariosaenger** [comment]
Hi @minstar ,

can you describe in a little more detail how you do the processing? One issue that occurs to me ad hoc: do you create a distinct SciSpacyTokenizer object for each sentence / document? Re-using the tokenizer saves a lot of processing time (since otherwise the SciSpacy model is loaded from scratch each time):

```python
tokenizer = SciSpacyTokenizer()

sentence1 = Sentence("My first sentence with some cancer disease ...",use_tokenizer=tokenizer)
sentence2 = Sentence("My second sentence with some cancer disease ...",use_tokenizer=tokenizer)
```

**Comment by minstar** [comment]
Oh! thanks for pointing out
I will try and solve this issue if it is the only problem.

**Comment by alanakbik** [comment]
@minstar please let us know if that solved the problem!

**Comment by minstar** [comment]
Yes! this has solved my problem! 
Thanks
