### ISSUE TITLE
Input data for document-level features (FLERT)

### ISSUE THREAD

**Issue by agademic** [flairNLP/flair#2348]
As I understand, to train a model which includes document-level features, we can set use_context=True in TransformerWordEmbeddings (is that correct?). 

My question is how do I pre-process the input data to allow the model to see the actual document boundaries? With a special token such as -DOCSTART-?

In your paper, you write that you add 64 subtokens prior and after the current sentence, but if the model doesn't know the actual document boundary, some tokens may come from two different documents.

Any hint is appreciated!

**Comment by alanakbik** [comment]
Hello @agademic if document boundaries are marked up and `respect_document_boundaries=True` then context will stop at document boundaries. Otherwise it is possible that the context would come from a different document. 

The `ColumnCorpus` object lets you define a token that signals the end of a document using the `document_separator_token` field. For CoNLL-03 for instance we set `document_separator_token="-DOCSTART-"`The separator token in the current implementation needs to be a separate sentence consisting only of that token.

**Comment by agademic** [comment]
Great! Thanks a lot for the clarification!
