### ISSUE TITLE
Use of TARS Classifier for use with adding new class without training data

### ISSUE THREAD

**Issue by sukannyapurkayastha** [flairNLP/flair#2388]
Hi,
  I would like to simulate the experiment for adding a new class without training data as in Sec 3.2 of the paper 'Task-Aware Representation of Sentences for Generic Text Classification' for our own dataset. I have already trained the model with the known classes, how should I finetune the same model on the new class data since the label_dictionary would change now. Can someone kindly guide me regarding this?

**Comment by kishaloyhalder** [comment]
Hi @sukannyapurkayastha ,

Thanks for the question! 

You can find the tutorial to achieve the same [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md#use-case-2-classify-text-with-very-little-training-data-few-shot). In your case, since you have already trained the model on some classes, please load that model instead of the `tars-base` model. So in the code, consider replacing `tars = TARSClassifier.load('tars-base')` with `tars = TARSClassifier.load('/path/to/your/tars-model.pt')`

Hope this helps.

with regards,
Kishaloy

**Comment by sukannyapurkayastha** [comment]
Thanks for your reply, Kishaloy. It's working just fine.
