### ISSUE TITLE
Can we evaluate a corpus using'hunflair' model?

### ISSUE THREAD

**Issue by NilakshanKunananthaseelan** [flairNLP/flair#2414]
I would like to performance metrics for the evaluation on the test set of NCBI datasets. Can I use hunflair model for this?

`AttributeError: 'MultiTagger' object has no attribute 'evaluate'`

I got the above error. Should I finetune the model again?

**Comment by mariosaenger** [comment]
Hi @NilakshanKunananthaseelan,

no - you don't have to fine-tune the model again. The problem here is that the HunFlair tagger actually consists of 5 individual taggers (one per entity type). If you want to evaluate the taggers you can do the following:

```python 
from datasets import NCBI_DISEASE
from models import MultiTagger

hunflair_tagger = MultiTagger.load("hunflair")
disease_tagger = hunflair_tagger.name_to_tagger["hunflair-disease"]

ncbi_disease = NCBI_DISEASE()
print(disease_tagger.evaluate(ncbi_disease.test, "ner"))
```
In the output you will find the score for the respective tagger (in this case the disease tagger):
```
...


By class:
              precision    recall  f1-score   support

     Disease     0.9719    0.9719    0.9719       960
```
If you have a corpus with multiple entity types, unfortunately you have to evaluate the individual taggers separately .

Does that help you?

**Comment by NilakshanKunananthaseelan** [comment]
I did the same, but the tagger has single label. I thought I can do  evaluation similar to CoNLL data so that I can have metrics for Disease,Gene,Species labels

I finetuned the datasets separately and evaluate them.

**Comment by alanakbik** [comment]
@NilakshanKunananthaseelan unfortunately, at this point, you'd need to compute the numbers separately. We have a refactoring in the works that will let you evaluate all hunflair taggers at once, but that will likely only be included in the next major flair release (and I cannot yet say when that will happen).

**Comment by NilakshanKunananthaseelan** [comment]
@alanakbik Thanks, I did the manual calculations.
