### ISSUE TITLE
about Fasttext in your paper <HunFlair: An Easy-to-Use Tool for State-of-the-Art Biomedical Named Entity Recognition>

### ISSUE THREAD

**Issue by zingxy** [flairNLP/flair#2452]
**_HunFlair: An Easy-to-Use Tool for State-of-the-Art Biomedical Named Entity Recognition_**
this paper said that you used _fasttext_ to train word embedding.  I‘m confused that  **Flair** framework have` FastTextEmbeddings` and 
`WordEmbeddings`, but your example about training _hunflair_ from scratch using ` WordEmbeddings("pubmed"),` to load word embedding. 
Why not` FastTextEmbedding`?

**Comment by helpmefindaname** [comment]
WordEmbeddings can use the embeddings created by FastText but have a <unk> token.
FastTextEmbeddings actually calculate the sub-n-gram out of vocabulary vector whenever needed. Therefore, FastTextEmbeddings need way more memory (storage for all the n-grams) and also needs more computation.
Without being an Author of HunFlair, I'd suppose that they either didn't want to stack up the requirements and didn't try out FastTextEmbeddings, or they tried it out without seeing an improvement (as it can lead to overfitting too)

**Comment by alanakbik** [comment]
Hello @zingxy, as @helpmefindaname writes FastText embeddings can be used in two ways: as regular word embeddings or as embeddings with ngram features. We typically use them as regular word embeddings and so load them with the class `WordEmbeddings`. If you also want to use the ngram features for out-of-vocabulary handling, you should use the `FastTextEmbedding` class instead. In our limited experiments, as well as experience from other researchers, the ngram features do more harm than help, which is why we do not use them.
