### ISSUE TITLE
Setting token embeddings on `Sentence` when using a classifier

### ISSUE THREAD

**Issue by DeNeutoy** [flairNLP/flair#2469]
A clear and concise description of what you want to know.

Hello! Thank you for the excellent library, in particular the zero shot model. I am constantly impressed by the detailed and useful work coming out of Zalando research. I was wondering - I would like to retain the token embeddings of the sentence when using the Flair Classifiers - is there a flag for this? 

e.g 

```python

tars = TARSModel.load("tars-ner")
sent = Sentence("My example sentence.")

tars.predict(sent)

# This is an empty tensor, but I would like it to be populated with the
# detatched contextual word vectors that the model uses
sent[0].embedding
```

I tried passing `store_embedding_mode="cpu"` as a flag to predict, but this seemed not to change the result. Is this possible?

Additionally - I would be happy to contribute a proper docs page, which can be deployed on github, as I have done it before for AllenNLP. A first version of this should be straightforward as it can be produced from markdown files, and your current tutorials are in markdown format.

Thanks!

**Comment by alanakbik** [comment]
Hello @DeNeutoy yes, but this currently only works for non-TARS classes, like `TextClassifier` or `SequenceLabeler`. The trick is like you wrote to set the `embedding_storage_mode` to CPU or GPU.

```python
from flair.data import Sentence
from flair.models import TextClassifier, SequenceTagger

# -----------------------------------------------------------
# Example 1: Standard Flair Classifier
# -----------------------------------------------------------
classifier: TextClassifier = TextClassifier.load("sentiment-fast")

# predict on example sentence with embedding storage mode set to "cpu"
sentence = Sentence("Very positive sentiment.")
classifier.predict(sentence, embedding_storage_mode="cpu")

# print embedding (works, prints embedding)
print(sentence.embedding)

# -----------------------------------------------------------
# Example 2: Standard Flair Sequence Tagger
# -----------------------------------------------------------
tagger: SequenceTagger = SequenceTagger.load("ner-fast")

# predict on example sentence with embedding storage mode set to "cpu"
sentence = Sentence("Very positive sentiment.")
tagger.predict(sentence, embedding_storage_mode="cpu")

# print embedding of first token in sentence (works, prints embedding)
print(tagger[0].embedding)
```

However, for TARS-like classes this currently doesn't work. The reason is that TARS models produce multiple embeddings for each sentence, i.e. one embedding for each combination of a sentence and the label to be predicted. We'd need to adapt the logic such that these embeddings get written back into the original sentence. Is this something you need? 

Regarding the other issue: proper docs would be great and we'd appreciate any help! Would it be docs like [this](https://docs.allennlp.org/main/api/data/data_loaders/data_collator/)?
