### ISSUE TITLE
using `TransformerWordEmbeddings`

### ISSUE THREAD

**Issue by zingxy** [flairNLP/flair#2500]
**Describe the bug**
when I used Huggingface model ''dmis-lab/biobert-base-cased-v1.2'' to embed a sentence, it raises  `OverflowError: int too big to convert`. And model `bert-base-cased`  works.

**To Reproduce**

```
bert = TransformerWordEmbeddings('bert-base-cased')
# biobert was trained on pubmed and pmc corpus.
biobert = TransformerWordEmbeddings('dmis-lab/biobert-base-cased-v1.2')
bert.embed(Sentence('hello'))
biobert.embed(Sentence('hello'))
```

**Expected behavior**

**Screenshots**
```
>>>bert.tokenizer
PreTrainedTokenizerFast(name_or_path='bert-base-cased', vocab_size=28996, model_max_len=512, is_fast=True, padding_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})
>>>biobert.tokenizer
PreTrainedTokenizerFast(name_or_path='dmis-lab/biobert-base-cased-v1.2', vocab_size=28996, **model_max_len=1000000000000000019884624838656**, is_fast=True, padding_side='right', special_tokens={
```
The biobert tokenizer's **model_max_len** may  cause this error, but I don't know how to fix this bug.

**Comment by whoisjones** [comment]
hi @zingxy,

it seems that BioBert has no model_max_length set. If you set the respective parameter `model_max_length` of huggingface's Tokenizer class to `512`, it works. However, this should be fixed in the config file of BioBert I guess.

`biobert = TransformerWordEmbeddings('dmis-lab/biobert-base-cased-v1.2', model_max_length=512)`

See also related issues: [hf-9317](https://discuss.huggingface.co/t/cannot-create-an-identical-pretrainedtokenizerfast-object-from-a-tokenizer-created-by-tokenizers-library/9317) and gh-2305

**Comment by zingxy** [comment]
@whoisjones Thank you for your detailed answer. According to your method, I solved the problem. Thank you.
