### ISSUE TITLE
Multicorpus training objective

### ISSUE THREAD

**Issue by MinskAndBoo** [flairNLP/flair#2553]
When training a MultiCorpus multilabel TARS classification task, we haven't found detailed documentation about how the model interprets the corpora - we have been through the tutorials and torch ConcatDataset documentation. We have two tasks, one with ~100K and one with ~1K samples. The first task is a 'filter' to 1% and the next task refines that 1% to about 0.5%. We are investigating how to combine these to get a reliable, consistent TARS model. We've implemented MultiCorpus models but it's not clear how they are working or what they are doing. 

Specifically: 
- How are the samples weighted from the two corpora? 
- Is there one underlying transformer and multiple heads? 
- Are counter-examples for the binary classifier drawn from other corpora? 
- Is there a conflict if the same label is used in more than one corpus? 

Any other insight or docs would be great. TARS works well for our problem so we appreciate your work and help on this.

**Comment by whoisjones** [comment]
hi @MinskAndBoo,

that depends on what your goal is: if you first train on one task and after that on the other one, you can do so by using TARS' function `add_and_switch_to_new_task()`. For this approach you do not need a multicorpus, simply create corpus 1 and corpus 2 and pass them accordingly. A Multicorpus takes all samples from each corpus by default and concats them into one large train, test and dev split respectively. This can be used to train models in parallel instead of sequentially. However, TARS is currently not designed that way to learn task simultaneously due to its negative sampling learning objective.

Regarding your other questions:

- Samples are not weighted by default. You can do so i.e. by downsampling the distinct corpora.
- One underlying transformer + one binary classification head. TARS transforms all its inputs into premise - hypothesis pairs such that a binary prediction is possible for every data set.
- In case of a MultiCorpus, yes counter-examples could also be drawn from the other corpora.
- Technically that should work (in case of MultiCorpus) because TARS recognizes the second label as the same from previous corpora. If you use normal corpora, that is not an issue. However, I am not sure about the behavior during training when using MultiCorpus.
