### ISSUE TITLE
 PicklingError: Could not serialize object: AttributeError: 'LanguageModel' object has no attribute 'document_delimiter'

### ISSUE THREAD

**Issue by MichSteczko** [flairNLP/flair#2554]
Hello, 
I tried to use Flair with PySpark, but when I am using UDF (user defined function) to iterate over column to extract dates from text, I am getting the following error:
 PicklingError: Could not serialize object: AttributeError: 'LanguageModel' object has no attribute 'document_delimiter'.
 My code:
`from flair.data import Sentence`
`from flair.models import SequenceTagger`
`from pyspark.sql.functions import udf`
 `tagger = SequenceTagger.load('ner-ontonotes-fast') `

 `def extract_dates(sent):  ` 
   `    sentence = Sentence(sent)`
    `   tagger.predict(sentence)`
    `   return [entity.text if entity.tag == 'DATE' and entity.score >= 0.7 else None for entity in sentence.get_spans('ner') ]`
`transform_udf = udf(lambda x: extract_dates(x), ArrayType(StringType()))
df.withColumn('Dates', transform_udf(col('Text')))`

Can I fix this error or is this just a bug?

**Comment by Tarotis** [comment]
I receive a similar error, but in my case while training a (custom) corpus and calling the trainer.train() function:

```
corpus = UD_ENGLISH().downsample(0.01)
tagger = SequenceTagger.load("pos-multi-fast")
trainer = ModelTrainer(tagger, corpus)
trainer.train('resources/taggers/example-upos', learning_rate=0.1, mini_batch_size=8, max_epochs=20)
```

Error is found in: `/flair/trainers/trainer.py", line 711, in train
    self.model.save(base_path / "best-model.pt", checkpoint=save_optimizer_state)`
Error message: `torch.nn.modules.module.ModuleAttributeError: 'LanguageModel' object has no attribute 'document_delimiter'`

The problem is reproduced when using the UD_ENGLISH() corpus instead of my custom data.

Package versions as followed: `flair: 0.10` and `torch: 1.9.1`, also tried `1.7.1` for torch and `0.9` for flair.

**Comment by rayamoh** [comment]
Hi @MichSteczko - Hope all is well. Wondering what was the performance with pyspark FlairNLP. We are running into performance issues , for 1 record it runs for 7 mins. Spark cluster (64 cores , 512GB memory). Can you please share your experience. Thanks!
