### ISSUE TITLE
Context when predicting with FLERT models

### ISSUE THREAD

**Issue by tsproisl** [flairNLP/flair#2650]
A clear and concise description of what you want to know.
I trained a FLERT-style model, i.e. I used `use_context=True` in `TransformerWordEmbeddings`. As I understand the paper, this uses the immediate context of each sentence, i.e. the tokens that occur to the left and right of the sentence in the original text.

In order to make predictions, I create a list of `Sentence` objects and pass the list to the `predict` method of the `SequenceTagger` method. As mentioned by @alanakbik in issue #2350:
> the tagger will automatically consider all sentences within the same mini-batch to belong to the same document. So you essentially have document context automatically.

However, as far as I understand the code, a mini-batch does not contain consecutive sentences but sentences of roughly equal length. Instead of getting the immediate context (as in training), the model gets potentially less useful context from anywhere in the document. If that is indeed the case, is there some possibility of giving the model the local context for prediction?

**Comment by alanakbik** [comment]
Hello @tsproisl thanks for noticing this - it is indeed a problem. The `predict` method in the `SequenceTagger` first reorders all sentences according to length and then makes the mini-batches. This means that actual context information is lost, since context is only considered by mini-batch. 

I guess one immediate workaround would be to do the mini-batching outside the predict method: 

```python
dataloader = DataLoader(
    dataset=FlairDatapointDataset(sentences),
    batch_size=32,
)

for batch in dataloader:
    ner_tagger.predict(batch, mini_batch_size=32)
```

Medium-term, we do need a better solution for this in Flair. Perhaps we should remove the batching from the `predict()` method altogether? Or we only remove the sorting.

**Comment by tsproisl** [comment]
Thank you for the answer and the workaround!
