### ISSUE TITLE
How multilingual data is handled with CRF layer by sequence tagger.

### ISSUE THREAD

**Issue by ayyoobimani** [flairNLP/flair#2677]
[This tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md)  suggests that to train a multilingual sequence tagger, all we need to do is to use a MultiCorpus object and use multilingual embeddings. 

My understanding of CRFs is that it stores a transition matrix that should be unique for each language. for example, the probability of having a noun after an adjective in German is different from English. I wonder if flair's multilingual sequence tagger handles it or not! And if yes could you, please refer me to the part of the code that handles it?

Thanks in advance.

**Comment by alanakbik** [comment]
Hello @ayyoobimani you're right: in this case, the CRF probably does not make much sense because of the different transition probabilities per language. But in general, we found that the CRF does not improve performance much for POS tasks over just using an RNN. So for multilingual POS tagging, I'd recommend just using the RNN. 

There will soon also be an option for true multi-task learning in which you'll also be able to specify different CRFs per language, though it won't make it into the upcoming release (probably the one after that).

**Comment by ayyoobimani** [comment]
Thanks a lot :)
