### ISSUE TITLE
Can I convert the flair fine-tuned model into a hugging face model?

### ISSUE THREAD

**Issue by kaliaanup** [flairNLP/flair#2685]
Hi I have created a flair fine-tuned model and I want to convert it into a HuggingFace representation. How can I do it?

**Comment by HallerPatrick** [comment]
Hey!

Not sure what you mean with HuggingFace representation, but if you want to add a model to HuggingFace, then I think you can look at [this](https://huggingface.co/docs/transformers/add_new_model). Otherwise here is a tutorial for [converting your model for all frameworks](https://huggingface.co/docs/transformers/add_new_model).

Greetings,
Patrick

**Comment by kaliaanup** [comment]
Thanks. Following is an example of a flair based fine-tuned model.

<img width="155" alt="Screen Shot 2022-03-23 at 1 07 00 PM" src="https://user-images.githubusercontent.com/8302569/159756100-987888dd-55d6-4c13-8b42-3946397b2176.png">

Following is an example of HuggingFace based fined tuned model.

<img width="217" alt="Screen Shot 2022-03-23 at 1 06 43 PM" src="https://user-images.githubusercontent.com/8302569/159756276-82af5d7d-1738-41b3-a59f-0e0825222f02.png">

Both are developed using the same train, dev and test datasets.

I can load the HuggingFace based fined tuned model as the following.

model_path = './results/checkpoint-14630'
BertForTokenClassification.from_pretrained(model_path)

Not sure if I can load the Flair model as it is. That's why I asked the question.

**Comment by kaliaanup** [comment]
Thanks !!
