### ISSUE TITLE
Best practice to update TARS classification model

### ISSUE THREAD

**Issue by snowneji** [flairNLP/flair#2923]
**[Context]** I initially trained a TARS model for text classification. But soon I received a new batch of data contains the new labels that the initial model doesn't have.  I found I cannot just keep training the model because it will throw me an `KeyError` that the new label doesn't exist in the corpus. I've been leaning towards creating a new task for the new batch of training data but I'm afraid it's not the best way of doing this.

**[Question]** 
 - What is the best practIce to update the trained TARS model for additional new labels and some new batch of training data in such scenario? 
 - Is there a way to update the TARS model without completely retrain it?

**Comment by alanakbik** [comment]
Hello @snowneji good question - your options are: 

1. create a new task only for the new batch. In this case you need not retrain the full model, and this is how TARS is intended to be used: learn new labels with few examples.
2. either train a new TARS model from scratch or create a new task for the old+new data. You could use this option if the new batch also contains the old labels. The new task will then be able to predict old and new, and the TARS model will be better extensible to new few-shot labels. 
3. use a regular TextClassifier instead of TARS: use this if you think the label set is complete and no new few-shot labels will be added in the future.

**Comment by snowneji** [comment]
Thanks, the question is solved.
