### ISSUE TITLE
Tokenizer inserting spaces

### ISSUE THREAD

**Issue by rxjx** [flairNLP/flair#2940]
Spaces seem to get added when converting strings into Sentences.

```
from flair.data import Corpus, Sentence

txt = ["X only has $7k USD, can't buy any GOOGL",
       'MSFT +6% after market again on strong cloud',
       "I'm expecting a jump in GOOGL"]
s = [Sentence(t) for t in txt]
s
```

Expected:
[Sentence: "X only has $7k USD, can't buy any GOOGL",
 Sentence: "MSFT + 6% after market again on strong cloud",
 Sentence: "I'm expecting a jump in GOOGL"]

Got:
[Sentence: "X only has $ 7k USD , ca n't buy any GOOGL",
 Sentence: "MSFT + 6 % after market again on strong cloud",
 Sentence: "I 'm expecting a jump in GOOGL"]

Google Colab
Flair 0.11.3

This insertion of spaces does not happen when reading in the same data as a ColumnCorpus from BIO annotated files.

**Comment by helpmefindaname** [comment]
Hi @rxjx
Notice there are multiple ways to get the text of a sentence:
```
sent.to_tokenized_string() # "X only has $ 7k USD , ca n't buy any GOOGL"
sent.to_tagged_string()  # 'Sentence: "X only has $ 7k USD , ca n\'t buy any GOOGL"'
sent.to_palin_string()  # "X only has $7k USD, can't buy any GOOGL"
sent.to_original_string()  # "X only has $7k USD, can't buy any GOOGL"
```

when you just use `str(sent)` it returns `self.to_tagged_string()`.
When you read the data from a ColumnCorpus, you have split the sentence in tokens by yourself. If you use `Sentence(text)` you will use the `SegtokTokenizer()`. You can provide tokens instead of text to the sentence to have it use the tokenization you expect (e.g. `Sentence(["X", "only", "has", $7k", "USD,", "can't", "buy", "any", GOOGL"])`)
