### ISSUE TITLE
connection timeout 

### ISSUE THREAD

**Issue by amod99** [flairNLP/flair#3015]
getting connection timeout error while trying to download 'en-sentiment' model. 

<img width="984" alt="image" src="https://user-images.githubusercontent.com/6858237/206390383-6d3e754d-b5ca-4916-aa93-72f07a351442.png">

**Comment by laura-jan** [comment]
Hi, same here

**Comment by laura-jan** [comment]
Error still persists 2 days in the row now and breaks the ml pipeline we have. Cam someone check this? HTTPSConnectionPool(host='flair.informatik.hu-berlin.de', port=443): Max retries exceeded with url: /resources/embeddings/token/no-wiki-fasttext-300d-1M.vectors.npy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6a12d4f7d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by stefan-it** [comment]
I've just forward that issue to the Flair team :)

**Comment by alanakbik** [comment]
Hello all, it seems we are getting unprecedented numbers of requests that are too much for the university servers. We are looking into this.

**Comment by kimchankyo** [comment]
Hi, could I ask for a status update on the server connection issue? I have a time sensitive project that relies on a Flair model and would like to know if it is possible to use by today. Thank you.

**Comment by laura-jan** [comment]
Thanks! It seems to be working again, at least for me.

**Comment by alanakbik** [comment]
Should be working again, please let us know if the problem returns!

**Comment by phamthienvuong98** [comment]
@alanakbik  Could you check again? Maybe this error has appeared
