### ISSUE TITLE
[Question]: where Flair 0.14+?

### ISSUE THREAD

**Issue by muqishan** [flairNLP/flair#3483]
### Question

`HunFlair2 is based on Flair 0.14+ and Python 3.8+.`
Sorry to bother you in your busy schedule. When I was using hunflair2, it prompted that flair>0.14 was required, but I could not find any version information about `flair>0.14.` I hope to use hunflair2. Thank you.

**Comment by alanakbik** [comment]
Hi @muqishan, I agree that we should release soon. The current semester ends in two weeks, after this there should be more time to focus on the next releases of HunFlair and Flair.

**Comment by muqishan** [comment]
Thank you, your work is vital in medical research.

> 嗨，我同意我们应该尽快发布。本学期将在两周后结束，在此之后应该有更多时间专注于 HunFlair 和 Flair 的下一个版本。

Thank you, your work is vital in medical research.

**Comment by muqishan** [comment]
> 谢谢你，你的工作在医学研究中至关重要。
> 
> > 嗨，我同意我们应该尽快发布。本学期将在两周后结束，在此之后应该有更多时间专注于 HunFlair 和 Flair 的下一个版本。
> 
> 谢谢你，你的工作在医学研究中至关重要。

Regarding `hunflair/hunflair2-ner` on huggingface, is it the implementation of the hunflair2 model introduced in the document?

`from flair.models.prefixed_tagger import PrefixedSequenceTagger`

Where can I get the implementation of this method? Or if I want to use this model, what kind of pre-processing and post-processing should I do?

**Comment by alanakbik** [comment]
@WangXII or @sg-wbi can you answer this?

**Comment by WangXII** [comment]
Hi @muqishan, yes, the `hunflair/hunflair2-ner` model indeed corresponds to the hunflair2 model introduced in the preprint document.

Regarding the `PrefixedSequenceTagger`, you can find the implementation of it [here](https://github.com/flairNLP/flair/blob/a852bff2b8c3cab3dcf7bd19fb1c528225816bf6/flair/models/prefixed_tagger.py). This is just a convenience class so that you don't have to add the prompt "Tag cell lines, chemicals ..." yourself in front of every sentence. To get an overview how to use the class, have a look at this updated HunFlair2 NER tutorial [here](https://github.com/flairNLP/flair/blob/a852bff2b8c3cab3dcf7bd19fb1c528225816bf6/resources/docs/HUNFLAIR2_TUTORIAL_3_TRAINING_NER.md`).

Let me know if you have any other questions left!

**Comment by muqishan** [comment]
> 嗨，是的，该模型确实对应于预印本文档中介绍的 hunflair2 模型。`hunflair/hunflair2-ner`
> 
> 关于 ，您可以[在此处](https://github.com/flairNLP/flair/blob/a852bff2b8c3cab3dcf7bd19fb1c528225816bf6/flair/models/prefixed_tagger.py)找到它的实现。这只是一个方便的类，因此您不必添加提示“标记细胞系，化学品......”你自己在每一句话前面。要大致了解如何使用该类，[请在此处](https://github.com/flairNLP/flair/blob/a852bff2b8c3cab3dcf7bd19fb1c528225816bf6/resources/docs/HUNFLAIR2_TUTORIAL_3_TRAINING_NER.md)查看此更新的 HunFlair2 NER 教程。`PrefixedSequenceTagger`
> 
> 如果您还有其他问题，请告诉我！

I solved the problem according to your method, thank you~

**Comment by MattGPT-ai** [comment]
I think this ticket can be closed
