### ISSUE TITLE
Word embeddings from Pubmed and PMC

### ISSUE THREAD

**Issue by gccome** [flairNLP/flair#552]
Can we consider adding word embeddings for biomedical filed? Various related w2v can be downloaded at http://evexdb.org/pmresources/vec-space-models/

More intro can be found at http://bio.nlplab.org

**Comment by alanakbik** [comment]
Good point! Yes, should be added!

**Comment by Bharat123rox** [comment]
@gccome PRs #519 and #503 already added the `FlairEmbeddings('pubmed-forward')` ,
`FlairEmbeddings('pubmed-backward')` and `ELMoEmbeddings('pubmed')` which I'm guessing is already from http://bio.nlplab.org in [this link](evexdb.org/pmresources/vec-space-models/PubMed-w2v.bin), but support for [PMC](evexdb.org/pmresources/vec-space-models/PMC-w2v.bin), [Pubmed+PMC](evexdb.org/pmresources/vec-space-models/PubMed-and-PMC-w2v.bin) and [Wikipedia+Pubmed+PMC](evexdb.org/pmresources/vec-space-models/wikipedia-pubmed-and-PMC-w2v.bin) could be added, at the cost of making `FlairEmbeddings` or `ELMoEmbeddings` of those corpora very large (since the last two are more than 2 GB).
@alanakbik Any thoughts on adding support for the last two?

**Comment by gccome** [comment]
@Bharat123rox thanks for the info! What I meant is that we can call something like WordEmbedding('pubmed')
