### ISSUE TITLE
Best Way to Incorporate Numeric Features?

### ISSUE THREAD

**Issue by DWDuq** [flairNLP/flair#649]
I want to do document classification and while I obviously have text, I also have some non-text, numeric features that I'd like to incorporate into the classification.  Can someone advise me on how hard it would be to modify the code to do this and roughly where to start or what to do?

**Comment by alanakbik** [comment]
Hi @DWDuq - you could do this by implementing an embedding class that essentially produces an embedding vector consisting only of the numeric value. A good starting point is the `WordEmbeddings` class (https://github.com/zalandoresearch/flair/blob/abad7da384260f0b41bedb726af9785aebe196b6/flair/embeddings.py#L152). 

This class takes a sentence and embeds each word from a precomputed word embedding. You could do something similar, but instead of looking up a word embedding you could use the numeric value stored in a field of the Token. In particular, check the `_add_embeddings_internal` method of the `WordEmbeddings` class and how the field parameter is used here: https://github.com/zalandoresearch/flair/blob/abad7da384260f0b41bedb726af9785aebe196b6/flair/embeddings.py#L232-L258 

Such an implementation is very doable, but you would need to familiarize yourself a bit with how the embedding mechanism works in Flair. Are you using a publicly available dataset? If so, we could maybe help you get started.

**Comment by DWDuq** [comment]
Thanks for the response, Alan!  This seems like a potentially viable approach, but I'd like to use DocumentRNNEmbeddings, and since there are ~50 numeric features only tangentially related to the text that I'd like to incorporate, I'm concerned they might muddle or slow things for the RNN.  Is it perhaps better to add the numeric features as an input to the actual FF classification layer if possible? What do you think?

Unfortunately the data is not publicly available as it is my own amalgamation, but I appreciate the tentative offer.  Essentially each sample is just ~5,000 word document combined with ~50 numeric features.

**Comment by alanakbik** [comment]
Hello @DWDuq that's a good point - if I understand correctly you would like to combine `DocumentRNNEmbeddings` over text with document-level numeric features. In this case, as you wrote, it would probably best combine the numeric feature with the output of the text RNN. In Flair, we accomplish such combinations by 'stacking' embeddings, but currently offer this only on the word level (see `StackedEmbeddings`). For your use case, you would need to implement a similar mechanism for documents. Essentially, a StackedEmbedding just concatenates all embeddings in a list into a singular embedding. 

We could also have a look at some point, but a reference dataset with such a structure would be useful.

**Comment by DWDuq** [comment]
I see, thanks for the info and lead
