### ISSUE TITLE
How to speed up Bert Embeddings?

### ISSUE THREAD

**Issue by davidlenz** [flairNLP/flair#686]
When using Bert embeddings, the embedding generation is very slow compared to Bert-as-Service for example. I wonder whether this is purely due to me not optimally passing examples to Bert. I use the following code:

```python
from flair.embeddings import BertEmbeddings
from segtok.segmenter import split_single
import tqdm
import numpy as np

bert_embeddings = BertEmbeddings('bert-base-uncased')
text_list=['First Text. It has two sentences', 'Second text']
embeddings = []
for _txt in tqdm(text_list):

	if _txt == "":
                continue
	sentences = [Sentence(sent, use_tokenizer=True) for sent in split_single(_txt)]
	try:
		# embed the sentence(s) using document embedding
		bert_embeddings .embed(sentences)
	except Exception as e:
		print('ERROR')
		print(sentences)
		print(e)
		print()

	# take mean over sentence embeddings to get text embedding
	emb = np.mean([np.array(sent.get_embedding()) for sent in sentences], axis=0).tolist()
	embeddings.append(emb)
```

Thereby every text is passed to Bert as a collection of sentences. I guess speed-ups via better GPU utilization by passing larger chunks of text can be achieved on my end. I wonder whether there is anything else i can do to achieve better performance. For ~5000 texts the code runs in roughly 30 mins on a Titan V.

Besides, do i actually need the sentence splitting via segtok with Bert? Also it seems i run out of CUDA memory for every third example. 

EDIT: the CUDA Error i am facing is similar to #685

**Comment by ivankrstev7** [comment]
I also have a problem with NER training being too slow with BertEmbeddings. Usually I have around 200 samples per sec when not using BERT, otherwise I get something around 8 which is very slow. I tried to increase the batch size to speed things up and that helped a little, but I cannot increase it sufficiently because the GPU will get out of memory. Any ideas why is it too slow and how should I speed it up?
![image](https://user-images.githubusercontent.com/48191509/96335771-3ddf5380-107b-11eb-9203-3e394e4c19e7.png)
