### ISSUE TITLE
Does doc embedding support stop words?

### ISSUE THREAD

**Issue by mmaaww** [flairNLP/flair#699]
Does doc embedding support stop words? I can not find any document on that. 

If yes, how to provide a list of stop words? If no, is there any plan to add such support in the near future?

Cheers,

**Comment by alanakbik** [comment]
Hi @mmaaww - do you mean that the doc embeddings skip over stop words and only use the other words to compile a document embedding? Interesting idea - are there papers or methods that use this techinque? 

This is currently not supported; since document embeddings are typically trained on downstream tasks we expect that they learn to ignore the uninportant words. In cases where you cannot train on a downstream task this might be an interesting method to get better document embeddings though. We are probably not going to add this ourselves in the near future, but if you'd like to put in a PR to add this feature, we'd always appreciate it :)
