### ISSUE TITLE
Hyperparameter Optimization, loss vs score

### ISSUE THREAD

**Issue by khituras** [flairNLP/flair#701]
For hyper parameter optimization one can specify the value to be optimized for like this
```
param_selector = SequenceTaggerParamSelector(
    corpus,
    tag_type,
    'resources/hyperopt_results',
    max_epochs=50,
    training_runs=3,
    optimization_value=OptimizationValue.DEV_SCORE
)
```
where in this example the value to be optimized is set to `OptimizationValue.DEV_SCORE`. Frankly, I do not know what this score represents. I would have thought of it as some kind of complement to the DEV_LOSS, which I do know. So I would have thought "score: higher is better".

I have made some optimization runs with `optimization_value=OptimizationValue.DEV_SCORE` and noticed that lower scores correlate with higher performance on the test data and vice versa. No I'm puzzled as to what parameters to choose: Those with high scores or low scores?

From the data I have it seems clear that lower scores would be better with regards to the test data but then I wonder why we need `DEV_SCORE` and don't stick with 'DEV_LOSS' to begin with.

I'd by very happy about some explanation here, the code wasn't enlightening to me :-)

**Comment by isanvicente** [comment]
Hi there,
       I've been struggling with this as well. This is what I have concluded, but feel free to correct me if I'm wrong @alanakbik .
   Hyperparameter optimization is handled by the [Hyperopt](https://github.com/hyperopt/hyperopt) library. Hyperopt defines an objective function to **minimize** for the given parameter search space. Useful references: [ref1](https://github.com/hyperopt/hyperopt/wiki/FMin) and [ref2](https://medium.com/district-data-labs/parameter-tuning-with-hyperopt-faa86acdfdce).

 This objective function is defined in Flair [hyperparameter/parameter_selection.py#L75](https://github.com/zalandoresearch/flair/blob/7567710a6c99bc2f35a1302e58cbf20d723ce926/flair/hyperparameter/param_selection.py#L75) as follows when `optimization_value=OptimizationValue.DEV_SCORE` (micro avg f1) is selected:
https://github.com/zalandoresearch/flair/blob/7cd9b899fe0b28cb4f9a6cb5d5092e98a1f1911d/flair/hyperparameter/param_selection.py#L121

So, if I understand correctly, the `score` returned for each evaluation run by the optimizer corresponds in fact to the value of `1-dev_score`, and that is why lower is better. 
I also found it confusing, because I was expecting the value of score to be micro average f1 score on dev set, which should be the higher the better.

**Comment by alanakbik** [comment]
Hello @khituras and @isanvicente - first of all sorry for the belated reply (busy at NAACL). But you are right: When optimizing hyperparameters against dev data, you essentially choose which metric on the dev data you wish to optimize. If you go for the loss, then it should be lowest on the dev data. If you go for score, then for NER that refers to the F-score and that should be highest on dev data, but as @isanvicente pointed out, we instead minimize the 1 - F1 score so that in all cases, we minimize. 

As for why we should use F1-score instead of loss is actually a good question. I guess we are using F1 here since in the end that is the metric we care about. But I do believe lots of people perfer to use the loss in hyperparameter optimiztion. I do not believe we've done a proper comparison of the two, so if you have any experiments to share here please let us know!
