### ISSUE TITLE
Are the calculated perplexity values correct? They are very low.

### ISSUE THREAD

**Issue by styfeng** [flairNLP/flair#714]
I am using Flair to calculate perplexities for sentences on the "news-forward" language model and they are very low (averages of around 4-5 perplexity). I thought typically perplexity is much higher, like 20+ even for fluent sentences. Is there something wrong or something I am overlooking?

**Comment by alanakbik** [comment]
Hello @styfeng - thanks for pointing this out. This is because the current implementation calculates perplexity only at the character level. This is not directly comparable to word-level perplexity where the vocabulary (space of all possible words) is much larger, so word-level PPL is generally much larger than character level PPL. There are methods to calculate word-level preplexity even for character LMs but we haven't implemented it yet. If you're interested, we'd always appreciate a PR :)
