### ISSUE TITLE
What is the release date for v0.5

### ISSUE THREAD

**Issue by Dhanachandra** [flairNLP/flair#731]
A clear and concise description of what you want to know.

**Comment by alanakbik** [comment]
Yes good question :) I am hoping to have v0.4.2 out before NAACL, i.e. in two weeks. This will hopefully include streaming data loading, improvements to model training, new embeddings and a bunch of other features.

For v0.5 there is no specific deadline yet, but speed of development on Flair will probably increase once the EMNLP and NIPS deadlines are through next week and NAACL is over.

**Comment by Dhanachandra** [comment]
@alanakbik 
Will v0.4.2 support multi GPU?

**Comment by alanakbik** [comment]
For 0.4.2 that is unlikely, since we have problems with GPU utilisation we want to look into first before adding more GPUs. The only part of the code that is ready for multi-GPU now is the language model training part since it already uses DataLoaders and has 100% GPU utilization. 

But 0.4.2 will add PyTorch DataLoaders for classification and sequence labeling datasets, so it will prepare multi-GPU support in the future.
