### ISSUE TITLE
different document embeddings for same input

### ISSUE THREAD

**Issue by infehm** [flairNLP/flair#781]
Hi, I used the flair RNN document embedding, one with glove word embeddings, one with bert word embeddings (ber-base-uncased) and one with flair multi-forward and multi-backward word embedding. Only the RNN with flair embedding resulted in the same document embedding for same documents. Why do the embeddings of similar documents differ when using other word embeddings? And can I get similar embeddings for those?

**Comment by alanakbik** [comment]
Hello @infehm I think the problem is that the RNN document embeddings need to be trained on a downstream task to make sense, i.e. the RNN is randomly initialized and must be trained to make a sensible embedding out of a sequence of word embeddings. See the [RNN part in tutorial 5](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md#rnn) on this.

If you want to get sentence representations without training a downstream task, you could use `DocumentPoolEmbeddings` instead which [need not be trained](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md#pooling) (but are better when trained).
