### ISSUE TITLE
bert gives wrong dimension of each token

### ISSUE THREAD

**Issue by omerarshad** [flairNLP/flair#835]
Token embedding of bert is 768 when using "hugging face" implementation, whereas when i use flair, it gives 3072 dimensional vector for each token.

**Comment by stefan-it** [comment]
Hi @omerarshad,

you're right, be default Flair would return a shape of 3072 for each token. The reason is, that we use the output of the last four layers. The output for each layer is concatenated and so a final embedding size of 4 * 768 = 3072 is returned.

The corresponding line in the code is:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1476

When you want to use the output of the last layer, just specify it with:

```python
from flair.data import Sentence
from flair.embeddings import BertEmbeddings

s = Sentence("Berlin and Munich are nice citites .")
embeddings = BertEmbeddings('bert-base-cased', layers='-1')

embeddings.embed(s)

for token in s.tokens:
    print(token.get_embedding().shape)
```

It then should return `torch.Size([768])` for each token :)
