### ISSUE TITLE
Get Embeddings out of domain-specific text

### ISSUE THREAD

**Issue by ctrboundary** [flairNLP/flair#861]
Hey Guys

I'm trying to get word embeddings (one vector for each word) out of some domain-specific text and thought of fine-tuning pre-trained forward and backward LMs on my text then extracting word embeddings (averaging vectors of the same words to get one vector for each word) which is really time consuming and expensive

1- Is it possible to get embeddings while/after training ? (Omitting the extraction phase after training) 
2- Is there any way of getting one vector for each word using PooledFlairEmbedding ?
3- Does it make sense to train and then extract embeddings on the same text ?

**Comment by alanakbik** [comment]
Hello @ctrboundary interesting questions. 

You could train / fine tune LMs on a text and then use a pooling operation to distill a single embedding for each unique string in your domain specific text. The `PooledFlairEmbeddings` class would be one way of doing this: You would have to first embed all sentences in your corpus so that the aggregated representations get built up. Then, you could access the `word_embeddings` field of `PooledFlairEmbeddings` to get the pooled representations of each word. Careful though to pack a lot of memory or divide your corpus up otherwise it might exit with memory errors. 

It would be interesting to hear how well such embeddings work. You lose the advantages of context-sensitivity but still they might be quite powerful.
