### ISSUE TITLE
Very less features as compared to StanfordNLP.

### ISSUE THREAD

**Issue by gopalkalpande** [flairNLP/flair#888]
This library is great as compared to any other Library but it sucks not to have a lot of features.
These features should be there in the library: Co-Referencing, Dependency Parsing.
Plz add these features.

**Comment by alanakbik** [comment]
@gopalkalpande we'd be happy to add them however dependency parsing and coreference resolution are currently not high on the [feature list](https://github.com/zalandoresearch/flair/issues/563), at least from our side since we are focusing on other features. We'd very much welcome community contributions though! I'd also love to see an implementation of SRL in Flair, though again this is not a feature we are currently focusing on.
