### ISSUE TITLE
OOV

### ISSUE THREAD

**Issue by benjisympa** [flairNLP/flair#917]
Hi, thank you very much for the work !

I'm wondering when you do a StackedEmbeddings with Glove and Flair for example and one word is not in the Glove's vocabulary, what will happen ? Because Flair will have an embedding but not Glove ?

Just to be sure, FlairEmbeddings and Fasttext are the only word embeddings to have characters embeddings level ?
Elmo, Bert, Glove, etc doesn't have right ?

Many thanks.

**Comment by alanakbik** [comment]
Hi @benjisympa a number of embeddings work at the character level, including `FlairEmbeddings`, `BytePairEmbeddings`, `CharacterEmbeddings` and `FastTextEmbeddings`. Additionally, lots of newer embeddings have handling for OOV words, such as `ELMoEmbeddings` (falls back to character features for unknown words) and `BertEmbeddings` (subword features). Those embeddings that cannot handle unknown words simply return an empty vector, so GloVe will return a vector of zeros for unknown words. If you use GloVe in combination with FlairEmbeddings, then the zero vector will be stacked with the flair vector (which is no problem because the downstream task can learn to deal with this).
