### ISSUE TITLE
Can we train using multiple CPUs (parallellization) since Flair is implemented with Pytorch?

### ISSUE THREAD

**Issue by Wickky** [flairNLP/flair#936]

**Comment by severinsimmler** [comment]
I'm pretty sure PyTorch does CPU parallelization by default.

**Comment by Wickky** [comment]
@severinsimmler Thank you for your reply. Is there any way to check for making sure of CPU parallelization while training in Flair?

**Comment by severinsimmler** [comment]
You could start training and check with e.g. `htop` if more than one CPU is used.

**Comment by BernierCR** [comment]
What about multiple GPUs? PyTorch supports that, so how much is needed to make Flair support it?

**Comment by alanakbik** [comment]
There are several ways of adding multi-GPU support. One is with the built-in DataParallel classes of PyTorch (see #848), the other is using Horovod (see #859). We are still evaluating which is the best way to go here, but currently we tend to favor horovod since this is less invasive to the rest of the code and has more functionality. 

Automatic mixed precision was also added recently (see #934) and is in fact already merged to master. This gives huge speedups in training large language models on a single GPU.

**Comment by djstrong** [comment]
This is about Flair language model or other models (e.g. classification)? Any updates?
