### ISSUE TITLE
Bert and Elmo from Flair framework

### ISSUE THREAD

**Issue by fatimabs** [flairNLP/flair#954]
i'm trained my own model using falir embedding to sentence similarity task, then, to embedd sentence i tried: 
-DocumentPoolEmbeddings 
-DocumentRNNEmbeddings

if i want to compare flair to elmo and bert embedding, it'll be enough if i use  ELMo embeddings class and bert embedding class from the Flair framework to compare the differents embeddings ? or should i train a new models using Bert end elmo ?

**Comment by alanakbik** [comment]
@fatimabs most people use the pretrained ELMo and BERT models since it is generally too resource-intensive to train your own models. What sentence similarity task are you doing and how are you training the task?

**Comment by fatimabs** [comment]
This is an unsupervised approach based on estimate the similarity between 2 sentences using cosine similarity distance. I trained a LM on my Arabic Corpus using Flair embeddings.

**Comment by alanakbik** [comment]
Ah ok, if it is unsupervised, only `DocumentPoolEmbeddings` without fine-tuning will work. `DocumentRNNEmbeddings` need to be trained on something in order to make sense, so if you use them in an unsupervised task, they are randomly initialized and will make no sense.

One potentially interesting thing to look into is word mover's distance, which allows you to compute similarity of sentences based on their word embeddings. We haven't implemented it in Flair but there are libraries out there for this. I think this type of distance could be much more powerful in an unsupervised scenario than simple averaging of word embeddings as done in the `DocumentPoolEmbeddings`.

**Comment by fatimabs** [comment]
That's mean DocumentPoolEmbeddings is the simple sum of word's vector in the sentence or there is a difference between DocumentPoolEmbeddings and the sum of word's vector?

if i want to use word mover's distance a simple example is :

sentence_obama = 'Obama speaks to the media in Illinois'
sentence_president = 'The president greets the press in Chicago'
sentence_obama = sentence_obama.lower().split()
sentence_president = sentence_president.lower().split()
model = Word2Vec.load_word2vec_format('/data/w2v_googlenews/GoogleNews-vectors-negative300.bin.gz', binary=True)
distance = model.wmdistance(sentence_obama, sentence_president)

How can i replace model = Word2Vec.load_word2vec_format('/data/w2v_googlenews/GoogleNews-vectors-negative300.bin.gz', binary=True) by my own LM trained with flair embeddings ?

**Comment by alanakbik** [comment]
Yes `DocumentPoolEmbeddings` can do different pooling functions, i.e. mean pooling (mean of all word vectors) and min and max pooling. In classification scenarios, they can also be fine-tuned and this can make a big difference, but this is not possible in an unsupervised scenario. 

I haven't worked with this library, but maybe you can pass the vectors in directly?

**Comment by fatimabs** [comment]
i don't think , i'll try
