### ISSUE TITLE
Can Flair load pre-downloaded word embeddings instead of downloading a new one? to avoid connection timeout?

### ISSUE THREAD

**Issue by billlyzhaoyh** [flairNLP/flair#958]
I am trying to train a customised text classification model in flair and upon calling word_embeddings = [WordEmbeddings('twitter')], it kicks start downloading word embedding from gesim from https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings/twitter.gensim.vectors.npy. It says it can't find it in cache. Do I have to download it for the first time use? I am encountering some connection error issues when doing this.

Thank you!

**Comment by alanakbik** [comment]
@billlyzhaoyh yes the first time you load and embedding or one of the pre-trained models it gets automatically downloaded to your machine. After that, it just gets loaded locally, so there is no further need for downloading anything. 

Alternatively, you can use the link and download the embedding in a local folder. Then instead of passing the string 'twitter' you can pass the path to the downloaded model, so it will load this instead.
