### ISSUE TITLE
tkinter dependency required for new interactive matplotlib mode training_curves.py

### ISSUE THREAD

**Issue by aychang95** [flairNLP/flair#963]
Getting "No module named 'tkinter'" error due to new change in:
commit 7f2b568ce5d7c1240d2275a3710a89f86b73b201

Should add a tkinter dependency if continuing with this change.

**Comment by alanakbik** [comment]
@aychang95 thanks for pointing this out. It looks like I can also address this error by commenting out the line

```python
matplotlib.use("TkAgg") 
```

@SiewLinYap is "TkAGG" needed here? I seem to get the same image even if I don't change matplotlib to this.

**Comment by SiewLinYap** [comment]
@alanakbik no plots will be displayed in ipynb if keeping "Agg". That's the reason I changed it to "TkAGG" to have it displayed along rather than navigate to other directory and open up the png file to see how the plots are. Attached is the example when "Agg" was put back.

<img width="1098" alt="Screenshot 2019-08-06 at 11 32 31 PM" src="https://user-images.githubusercontent.com/35646492/62553814-9a08ee00-b8a2-11e9-8f42-d132d3b78fd2.png">

**Comment by BernierCR** [comment]
OK. But if you don't use a full blown jupyter server and web browser notebooks, then this can fail. Specifically, if you use iPython feature of VSCode "cell" mode, it will fail with TkAGG, because jupyter is running in headless mode in this case. 

I think this should be configurable. If someone wants to use a regular jupyter notebook to see their graphs, makes sense, that's the traditional Data Science workflow. But maybe just have them put a setting at the top of their notebook, or in the function call or something. 

Or be clever and somehow detect they are using jupyter in not headless mode.
